#ifndef ERRORS_H
#define ERRORS_H

enum error_types {
    ERROR_NO_ERROR,
    ERROR_LEXICAL_UNCLOSED_COMMENT,
    ERROR_LEXICAL_UNCLOSED_STRING,
    ERROR_LEXICAL_UNEXPECTED_CHARACTER,
    ERROR_SYNTAX
};

#endif // ERRORS_H
