/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
static yyconst short int yy_accept[317] =
    {   0,
        0,    0,    0,    0,    0,    0,   77,   76,    4,    2,
       76,   59,    5,    6,    9,    7,    8,   10,   21,   76,
        3,   13,   15,   11,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   71,   71,   72,   75,   72,    0,    0,    0,    0,
        1,   21,   21,   68,   68,   68,   68,   68,   68,   68,
        3,   14,   12,   69,   69,   69,   69,   69,   28,   69,
       69,   69,   69,   69,   49,   27,   69,   69,   69,   69,
       69,   17,   69,   69,   69,   69,   69,   69,   30,   69,
       69,   69,   69,   70,   73,   74,   23,   23,   23,   23,

       23,   23,   23,   23,   19,   20,   22,   68,   68,   68,
       68,   68,   68,   68,   16,   69,   69,   69,   69,   69,
       41,   69,   26,   69,   69,   37,   69,   69,   18,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,    0,    0,    0,    0,    0,    0,    0,    0,   68,
       68,   68,   68,   68,   68,   68,   69,   69,   69,   69,
       69,   69,   69,   44,   69,   29,   69,   42,   25,   53,
       69,   69,   69,   69,   36,   69,   69,   69,   69,   69,
       69,    0,    0,    0,    0,    0,    0,    0,   24,   68,
       68,   68,   68,   68,   66,   68,   54,   69,   43,   69,

       69,   51,   69,   69,   69,   69,   34,   69,   69,    0,
       69,   33,   69,   32,    0,    0,    0,    0,    0,    0,
        0,   68,   68,   68,   68,   68,   68,   68,   69,   69,
       69,   69,   56,   69,   69,   46,   31,    0,   69,   38,
        0,    0,    0,    0,    0,    0,   68,   68,   68,   68,
       68,   61,   62,   69,   69,   69,   50,   57,   69,    0,
       69,    0,    0,    0,    0,    0,   68,   68,   68,   64,
       68,   69,   58,   69,   45,    0,   69,    0,    0,    0,
        0,   63,   68,   68,   60,   69,   69,    0,   69,    0,
        0,    0,    0,   68,   68,   69,   69,   52,   47,   40,

        0,    0,   65,   68,   48,   69,   39,    0,   68,   35,
        0,   68,    0,   67,   55,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   14,   15,
       15,   15,   15,   15,   15,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   23,   33,   34,   35,   36,   37,   38,
       23,   39,   40,   41,   42,   43,   44,   45,   46,   23,
        1,   22,    1,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   23,   33,   34,   35,   36,
       37,   38,   23,   39,   40,   41,   42,   43,   44,   45,
       46,   23,    1,   47,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[48] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    5,    4,    4,    4,    4,    4,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1
    } ;

static yyconst short int yy_base[324] =
    {   0,
        0,    0,  312,  311,   44,   45,  357,  360,  360,  360,
       28,  360,  360,  360,  360,  360,  360,  360,   40,   37,
        0,  336,  360,  335,    0,  318,   23,   31,  319,   40,
       22,   52,  315,   24,   46,  323,   58,  313,  313,  320,
       39,  360,  342,  360,  360,   83,   63,  332,   76,    0,
      360,  360,   94,    0,   81,  308,  308,  315,  296,  302,
        0,  360,  360,    0,  313,  302,   75,  309,  296,  295,
      299,  295,  296,  296,    0,    0,  290,  290,  292,  287,
      299,    0,  286,  288,   58,  283,  286,  297,    0,  280,
      294,  287,  277,  360,  360,  360,  360,  293,  284,  287,

      290,   70,  275,  288,  297,   80,    0,  284,  275,  282,
      275,  282,  267,  272,    0,  263,  276,  265,   87,  268,
        0,  272,  263,  262,  270,    0,  254,  256,    0,  257,
      260,  261,  253,  261,  259,  246,  246,  253,  243,  249,
      251,  255,  244,  235,  248,  236,  251,  251,  249,  245,
      235,  229,  229,  242,  240,  226,  238,  241,  223,  229,
      238,  225,  225,    0,  235,    0,  234,    0,    0,    0,
      216,  220,  212,  230,    0,  242,  211,  217,  213,  221,
      237,  214,  218,  211,  216,  201,  205,  215,  360,  200,
      213,  203,   90,  209,    0,  208,    0,  194,    0,  210,

      194,    0,  204,  190,  196,  197,    0,  200,  186,  183,
      193,    0,  185,    0,  186,  182,  192,  188,  180,  176,
      189,  176,  191,  186,  174,  175,  172,  171,  181,  168,
      183,  166,    0,  171,  167,    0,    0,  179,  161,  190,
      162,  161,  170,  161,  160,  154,  157,  152,  156,  161,
      151,    0,    0,  153,  148,  152,    0,    0,  150,  151,
      142,  145,  154,  157,  152,  151,  139,  145,  135,    0,
      140,  150,    0,  145,    0,  130,  130,   79,  134,  143,
      141,    0,  130,  142,    0,  124,  123,  135,  134,  123,
      120,  148,  130,  121,  113,  125,  119,  360,    0,  360,

      111,   99,    0,   95,    0,   87,  360,   92,   86,    0,
       88,   84,   90,    0,  360,  360,  129,  134,  139,  144,
      146,  151,   70
    } ;

static yyconst short int yy_def[324] =
    {   0,
      316,    1,  317,  317,  318,  318,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  319,
      320,  316,  316,  316,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  316,  316,  316,  316,  316,  322,  316,  316,  323,
      316,  316,  316,  319,  319,  319,  319,  319,  319,  319,
      320,  316,  316,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  323,  319,  319,  319,
      319,  319,  319,  319,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  316,  316,  316,  316,  316,  316,  316,  316,  319,
      319,  319,  319,  319,  319,  319,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  316,  316,  316,  316,  316,  316,  316,  316,  319,
      319,  319,  319,  319,  319,  319,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  316,
      321,  321,  321,  321,  316,  316,  316,  316,  316,  316,
      316,  319,  319,  319,  319,  319,  319,  319,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  316,  321,  321,
      316,  316,  316,  316,  316,  316,  319,  319,  319,  319,
      319,  319,  319,  321,  321,  321,  321,  321,  321,  316,
      321,  316,  316,  316,  316,  316,  319,  319,  319,  319,
      319,  321,  321,  321,  321,  316,  321,  316,  316,  316,
      316,  319,  319,  319,  319,  321,  321,  316,  321,  316,
      316,  316,  316,  319,  319,  321,  321,  316,  321,  316,

      316,  316,  319,  319,  321,  321,  316,  316,  319,  321,
      316,  319,  316,  319,  316,    0,  316,  316,  316,  316,
      316,  316,  316
    } ;

static yyconst short int yy_nxt[408] =
    {   0,
        8,    9,    9,   10,   11,   12,   13,   14,   15,   16,
       17,    8,   18,   19,   19,   19,   20,   21,   22,   23,
       24,    8,   25,   26,   25,   27,   28,   29,   30,   25,
       25,   31,   25,   32,   25,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   25,   25,    8,   45,   45,   47,
       75,   52,   48,   53,   53,   53,   66,   76,   68,   67,
       55,   81,   82,   56,   49,   46,   46,   69,   57,   92,
       93,   71,   50,  107,   51,   58,   72,   59,   73,   77,
       60,   74,   83,   78,   84,   86,   95,   98,   79,  106,
      106,   87,  133,  106,  106,  134,   99,  146,  100,   88,

      101,  102,  103,  104,   96,   52,  108,   53,   53,   53,
      117,  147,  160,  225,  109,  290,  118,  315,  226,  314,
      291,  313,  312,  311,  161,  310,  309,  308,  162,   42,
       42,   42,   42,   42,   44,   44,   44,   44,   44,   54,
       54,  307,   54,   54,   61,   61,  306,   61,   61,   64,
       64,   97,  305,  304,   97,   97,  303,  189,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  189,  293,  292,
      289,  288,  287,  286,  285,  284,  283,  282,  189,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  189,  189,  266,  265,  264,  263,

      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  189,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  224,  223,  222,
      221,  220,  219,  189,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,

      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      105,  149,  148,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  116,  115,
      114,  113,  112,  111,  110,  105,   94,   91,   90,   89,
       85,   80,   70,   65,   63,   62,  316,   43,   43,    7,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316
    } ;

static yyconst short int yy_chk[408] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    6,   11,
       31,   19,   11,   19,   19,   19,   27,   31,   28,   27,
       20,   34,   34,   20,   11,    5,    6,   28,   20,   41,
       41,   30,   11,  323,   11,   20,   30,   20,   30,   32,
       20,   30,   35,   32,   35,   37,   46,   47,   32,   49,
       49,   37,   85,  106,  106,   85,   47,  102,   47,   37,

       47,   47,   47,   47,   46,   53,   55,   53,   53,   53,
       67,  102,  119,  193,   55,  278,   67,  313,  193,  312,
      278,  311,  309,  308,  119,  306,  304,  302,  119,  317,
      317,  317,  317,  317,  318,  318,  318,  318,  318,  319,
      319,  301,  319,  319,  320,  320,  297,  320,  320,  321,
      321,  322,  296,  295,  322,  322,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  284,  283,  281,  280,  279,
      277,  276,  274,  272,  271,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  256,  255,  254,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,

      240,  239,  238,  235,  234,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  213,  211,  210,  209,  208,  206,  205,
      204,  203,  201,  200,  198,  196,  194,  192,  191,  190,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  174,  173,  172,  171,  167,  165,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  128,  127,  125,  124,  123,  122,  120,

      118,  117,  116,  114,  113,  112,  111,  110,  109,  108,
      105,  104,  103,  101,  100,   99,   98,   93,   92,   91,
       90,   88,   87,   86,   84,   83,   81,   80,   79,   78,
       77,   74,   73,   72,   71,   70,   69,   68,   66,   65,
       60,   59,   58,   57,   56,   48,   43,   40,   39,   38,
       36,   33,   29,   26,   24,   22,    7,    4,    3,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "input.flex"
#define INITIAL 0
#line 2 "input.flex"

//#include "lexemtypes.h"

int my_powah(int base, int n)
{
    int result = 1;
    for (int i = 0; i < n; i++)
        result *= base;
    return result;
}

int nondec2dec(char * string, int base) {
    int result = 0;
    size_t length = strlen(string);
    for (size_t i = 0; i < length; i++)
    {
        char cur = string[length - i - 1];
        int tmp = 0;
        switch (cur)
        {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            tmp = (int)cur - 0x30;
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
            tmp = (int)cur - ('A' - 0xA);
            break;
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
            tmp = (int)cur - ('a' - 0xA);
            break;
        default:
            tmp = 0;
        }
        result += tmp * my_powah(base, i);
    }
    return result;
}

void buffer_output(char * title, char * buf, unsigned int len)
{
    printf("%s", title);
    for (unsigned int i = 0; i < len; i++)
        printf("%c", buf[i]);
    printf("\n");
}

#define YY_NEVER_INTERACTIVE 1
#define COMMENT_ML 1

#define STRING 2

#line 632 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 83 "input.flex"



char            buffer[8 * 1024];   // For storing strings, comments etc.
unsigned int    buffer_length = 0;  // Length of the buffer.


#line 791 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 360 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "input.flex"
{
    // Multiline comment beginning.
    buffer_length = 0;
    BEGIN(COMMENT_ML);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 95 "input.flex"
{
    // String constant beginning.
    buffer_length = 0;
    BEGIN(STRING);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 100 "input.flex"
{
    // Singleline comment.
    strcpy(buffer, yytext + 1);
    buffer_length = strlen(yytext + 1);
    buffer_output("Comment:                   ", buffer, buffer_length);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "input.flex"
{
    // Whitespaces.
    //printf("Skipping whitespace\n");
    //printf("Whitespace:  %s\n", yytext);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 111 "input.flex"
{
    // Opening parenthesis.
    printf("Opening paren:             %s\n", yytext);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 115 "input.flex"
{
    // Closing parenthesis.
    printf("Closing paren:             %s\n", yytext);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 119 "input.flex"
{
    // Operator: addition.
    printf("Operator add:              %s\n", yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 123 "input.flex"
{
    // Operator: subtraction.
    printf("Operator sub:              %s\n", yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 127 "input.flex"
{
    // Operator: multiplication.
    printf("Operator mult:             %s\n", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "input.flex"
{
    // Operator: division.
    printf("Operator div:              %s\n", yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 135 "input.flex"
{
    // Operator: greater.
    printf("Operator greater:          %s\n", yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 139 "input.flex"
{
    // Operator: greater or equal.
    printf("Operator greater or equal: %s\n", yytext);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 143 "input.flex"
{
    // Operator: less.
    printf("Operator less:             %s\n", yytext);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 147 "input.flex"
{
    // Operator: less or equal.
    printf("Operator less or equal:    %s\n", yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 151 "input.flex"
{
    // Operator: equal.
    printf("Operator equal:            %s\n", yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 155 "input.flex"
{
    // Operator: and.
    printf("Operator and:              %s\n", yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 159 "input.flex"
{
    // Operator: or.
    printf("Operator or:               %s\n", yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 "input.flex"
{
    // Operator: not.
    printf("Operator not:              %s\n", yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 167 "input.flex"
{
    // Numeric constant - binary.
    int value = nondec2dec(yytext + 2, 2);
    printf("Numeric constant - bin:    %d\n", value);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 172 "input.flex"
{
    // Numeric constant - octal.
    int value = nondec2dec(yytext + 2, 8);
    printf("Numeric constant - oct:    %d\n", value);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 177 "input.flex"
{
    // Numeric constant.
    if (yytext[yyleng - 1] == '.')
        yytext[yyleng - 1] = '\0';
    int value = nondec2dec(yytext, 10);
    printf("Numeric constant - dec:    %d\n", value);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 184 "input.flex"
{
    // Numeric constant - hexadecimal.
    int value = nondec2dec(yytext + 2, 16);
    printf("Numeric constant - hex:    %d\n", value);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 189 "input.flex"
{
    // Character constant.
    printf("Character constant:        %s\n", yytext + 2);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 193 "input.flex"
{
    // Character constant - whitespace.
    // TODO: convert to a real character.
    printf("Character constant:        %s\n", yytext + 2);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 198 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 201 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 204 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 207 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 210 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 213 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 216 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 219 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 222 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 225 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 228 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 231 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 234 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 237 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 240 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 243 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 246 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 249 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 252 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 255 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 258 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 261 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 264 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 267 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 270 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 273 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 276 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 279 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 282 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 285 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 288 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 291 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 294 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 297 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 300 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 303 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 306 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 309 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 312 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 315 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 318 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 321 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 324 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 327 "input.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 330 "input.flex"
{
    printf("Variable:                  %s\n", yytext);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 333 "input.flex"
{
    // Multiline comment ending.
    buffer_output("Comment:                   ", buffer, buffer_length);
    buffer_length = 0;
    BEGIN(INITIAL);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 339 "input.flex"
{
    // Multiline comment body: any character.
    buffer[buffer_length++] = yytext[0];
}
	YY_BREAK
case YY_STATE_EOF(COMMENT_ML):
#line 343 "input.flex"
{
    puts("ERROR: UNCLOSED COMMENT");
    yyterminate();
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 347 "input.flex"
{
    // String constant body: non-quote character.
    buffer[buffer_length++] = yytext[0];
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 351 "input.flex"
{
    // String constant body: escaped quote character.
    buffer[buffer_length++] = '"';
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 355 "input.flex"
{
    // String constant body: escaped slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 359 "input.flex"
{
    // String constant ending.
    buffer_output("String constant:           ", buffer, buffer_length);
    buffer_length = 0;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 365 "input.flex"
{
    puts("ERROR: UNCLOSED STRING CONSTANT");
    yyterminate();
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 370 "input.flex"
ECHO;
	YY_BREAK
#line 1464 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 316);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 370 "input.flex"


int main(int argc, char * argv[])
{
    yyin = fopen("text.txt", "r");
    if (yyin == 0)
        printf("error opening text.txt\n");
    else
    {
        yylex();
        fclose(yyin);
    }
    return 0;
}
