#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[342] =
    {   0,
        0,    0,    0,    0,    0,    0,   85,   74,    4,    4,
        2,   74,   73,   62,    5,    6,    9,    7,    8,   10,
       23,   74,    3,   13,   15,   11,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   19,   73,
       73,   73,   77,   76,   75,   81,   83,   82,    4,    0,
        0,    0,    0,    1,   73,   23,   23,   72,   72,   72,
       72,   72,   72,   72,    3,   14,   12,   73,   73,   73,
       73,   30,   73,   73,   73,   73,   73,   52,   29,   73,
       73,   73,   73,   73,   73,   17,   73,   73,   73,   73,
       73,   73,   32,   73,   73,   73,   73,   77,   78,   81,

       79,   80,   21,   22,   24,   25,   25,   25,   25,   25,
       25,   25,   25,   72,   72,   72,   72,   72,   72,   72,
       16,   73,   73,   73,   73,   43,   73,   28,   73,   73,
       73,   39,   73,   73,   20,   18,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,    0,
        0,    0,    0,    0,    0,    0,    0,   72,   72,   72,
       72,   72,   72,   72,   73,   73,   73,   73,   73,   73,
       47,   73,   31,   73,   73,   44,   27,   56,   73,   73,
       73,   73,   73,   38,   73,   73,   73,   73,   73,   73,
        0,    0,    0,    0,    0,    0,    0,   26,   72,   72,

       72,   72,   72,   70,   72,   57,   73,   73,   73,   54,
       73,   73,   73,   73,   73,   73,   63,   36,   73,   73,
       73,   73,   35,   73,   34,   73,    0,    0,    0,   26,
        0,    0,    0,   72,   72,   72,   72,   72,   72,   72,
       73,   73,   73,   73,   59,   73,   46,   73,   73,   49,
       33,   73,   73,   40,   73,    0,    0,    0,    0,    0,
       26,   72,   72,   72,   72,   72,   65,   66,   73,   73,
       73,   53,   60,   73,   73,   73,   73,   73,   73,    0,
        0,    0,   26,   26,   72,   72,   72,   68,   72,   73,
       61,   73,   73,   48,   73,   73,   73,   73,    0,    0,

       26,   67,   72,   72,   64,   73,   73,   73,   73,   73,
       73,   73,   73,    0,   26,   72,   72,   73,   73,   73,
       55,   50,   42,   73,   73,   26,   69,   72,   51,   73,
       45,   41,   73,   72,   37,   73,   72,   73,   71,   58,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    6,    6,    7,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,    1,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,    6,   32,   33,   34,   35,   36,   37,
        6,   38,   39,   40,   41,   42,   43,   44,   45,    6,
        1,   46,    1,    6,    6,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,    6,   56,   57,   58,   59,
       60,   61,    6,   62,   63,   64,   65,   66,   67,   68,
       69,    6,    1,   70,    1,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    2,    3,    4,    5,    6,    1,    1,    1,    6,
        6,    6,    6,    6,    7,    7,    7,    1,    1,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    4,    7,    7,    7,    7,
        7,    7,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    5
    } ;

static yyconst flex_int16_t yy_base[351] =
    {   0,
        0,    0,   66,   67,   69,   70,  632,  701,   73,   75,
      701,   57,    0,  701,  701,  701,    0,    0,    0,    0,
       67,  115,    0,  278,    0,  274,   50,   53,   60,   55,
       59,   71,   71,   97,  102,  106,   67,  118,   72,  108,
      120,  118,    0,  701,  208,    0,  701,   88,  158,  161,
      165,    0,  160,  701,    0,    0,  172,    0,  153,  114,
      155,  164,  147,  156,    0,    0,    0,  170,  165,  168,
      176,  165,  166,  172,  171,  175,  177,    0,    0,  197,
      187,  198,  205,  199,  213,    0,  202,  211,  209,  204,
      209,  224,    0,  209,  226,  221,  213,    0,  701,    0,

      701,  701,  141,  239,    0,  701,  234,  228,  233,  251,
      251,  242,  257,  257,  252,  261,  256,  265,  252,  259,
        0,  252,  268,  282,  263,    0,  270,  263,  266,  276,
      276,    0,  268,  285,    0,    0,  291,  296,  293,  301,
      297,  307,  307,  296,  298,  307,  299,  307,  311,  317,
      309,  302,  319,  309,  329,  332,  332,  340,  334,  330,
      334,  349,  349,  338,  354,  359,  350,  361,  350,  352,
        0,  364,    0,  365,  349,  142,    0,    0,  350,  352,
      358,  354,  374,    0,  123,  361,  370,  368,  388,  117,
      386,  392,  389,  396,  383,  390,  404,  701,  391,  406,

      398,  410,  407,    0,  408,    0,  396,  414,  402,    0,
      414,  404,  412,  419,  418,  421,    0,    0,  436,  426,
      425,  439,    0,  433,    0,  436,  435,  449,  447,  701,
      441,  439,  454,  443,  460,  457,  447,  450,  450,  451,
      465,  454,  474,  460,    0,  467,    0,  484,  478,    0,
        0,  492,  478,   92,  482,  483,  495,  490,  491,  487,
      701,  492,  489,  495,  502,  494,    0,    0,  498,  495,
      502,    0,    0,  502,  505,  508,  504,  510,  521,  536,
      535,  536,  701,  701,  528,  536,  528,    0,  536,  550,
        0,  547,  546,    0,  535,  537,  543,  543,  555,  555,

      701,    0,  546,  562,    0,  548,  549,  553,  568,  569,
      570,  571,   79,  584,  701,  579,  575,  589,  591,  591,
        0,    0,    0,  592,  595,  701,    0,  593,    0,  587,
        0,    0,  595,  591,    0,  595,  594,  603,    0,    0,
      701,  654,  661,  663,  665,  672,  679,  686,   72,  693
    } ;

static yyconst flex_int16_t yy_def[351] =
    {   0,
      341,    1,  342,  342,  343,  343,  341,  341,  341,  341,
      341,  341,  344,  341,  341,  341,  344,  344,  344,  344,
      344,  345,  346,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  347,  341,  341,  348,  341,  341,  341,  341,
      341,  349,  350,  341,  344,  344,  344,  345,  345,  345,
      345,  345,  345,  345,  346,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  347,  341,  348,

      341,  341,  341,  341,  349,  341,  341,  341,  341,  341,
      341,  341,  341,  345,  345,  345,  345,  345,  345,  345,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  341,
      341,  341,  341,  341,  341,  341,  341,  345,  345,  345,
      345,  345,  345,  345,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      341,  341,  341,  341,  341,  341,  341,  341,  345,  345,

      345,  345,  345,  345,  345,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  341,  341,  341,  341,
      341,  341,  341,  345,  345,  345,  345,  345,  345,  345,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  341,  341,  341,  341,  341,
      341,  345,  345,  345,  345,  345,  345,  345,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  341,
      341,  341,  341,  341,  345,  345,  345,  345,  345,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  341,  341,

      341,  345,  345,  345,  345,  344,  344,  344,  344,  344,
      344,  344,  344,  341,  341,  345,  345,  344,  344,  344,
      344,  344,  344,  344,  344,  341,  345,  345,  344,  344,
      344,  344,  344,  345,  344,  344,  345,  344,  345,  344,
        0,  341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static yyconst flex_int16_t yy_nxt[772] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   13,   20,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   13,   28,   29,   30,   31,   13,   13,
       32,   13,   33,   13,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   13,   13,    8,   27,   13,   28,   29,
       30,   31,   13,   13,   32,   13,   33,   13,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   13,   13,    8,
       44,   44,   47,   47,   49,   49,   49,   49,  105,   56,
       50,   57,   57,   57,   68,   69,   71,   73,   70,   74,
      325,  101,   51,   89,   75,   72,   76,   80,   78,   77,

       52,   81,   53,  278,   50,   79,   82,   93,   68,   69,
       71,   73,   70,   74,   48,   48,   51,   89,   75,   72,
       76,   80,   78,   77,   52,   81,   54,   83,  226,   79,
       82,   93,   84,  102,  221,   45,   45,   59,   85,   86,
       60,   87,   94,   88,   90,   61,   95,   96,   97,  116,
       91,   83,   62,  215,   63,  103,   84,   64,   92,   49,
       49,   59,   85,   86,   60,   87,   94,   88,   90,   61,
       95,   96,   97,  116,   91,  103,   62,  114,   63,  104,
      104,   64,   92,  107,   56,  115,   57,   57,   57,  117,
      118,  119,  108,  120,  109,  121,  110,  111,  112,  113,

      122,  114,  123,  124,  125,  126,  127,  107,  128,  115,
      129,  130,   99,  117,  118,  119,  108,  120,  109,  121,
      110,  111,  112,  113,  122,  133,  123,  124,  125,  126,
      127,  131,  128,  134,  129,  130,  132,  135,  136,  137,
      138,  139,  141,  143,  144,  142,  140,  145,  146,  133,
      147,  148,  149,  104,  104,  131,  150,  134,  151,  152,
      132,  135,  136,  137,  138,  139,  141,  143,  144,  142,
      140,  145,  146,  153,  147,  148,  149,  154,  156,  157,
      150,  158,  151,  152,  159,  160,  161,  162,  163,  164,
      165,  155,  166,  170,   67,  171,  172,  153,   66,  173,

      174,  154,  156,  157,  175,  158,  167,  176,  159,  160,
      161,  162,  163,  164,  165,  155,  166,  170,  168,  171,
      172,  177,  169,  173,  174,  178,  179,  180,  175,  181,
      167,  176,  182,  183,  184,  185,  186,  187,  188,  189,
      190,  191,  168,  192,  193,  177,  169,  194,  195,  178,
      179,  180,  196,  181,  197,  198,  182,  183,  184,  185,
      186,  187,  188,  189,  190,  191,  199,  192,  193,  200,
      201,  194,  195,  202,  203,  204,  196,  205,  197,  198,
      206,  207,  208,  209,  210,  211,  212,  213,  214,  216,
      199,  217,  218,  200,  201,  219,  220,  202,  203,  204,

      222,  205,  223,  224,  206,  207,  208,  209,  210,  211,
      212,  213,  214,  216,  225,  217,  218,  227,  228,  219,
      220,  229,  230,  231,  222,  232,  223,  224,  233,  234,
      235,  236,  237,  239,  240,  241,  242,  238,  225,  243,
      244,  227,  228,  245,  246,  229,  230,  231,  247,  232,
      248,  249,  233,  234,  235,  236,  237,  239,  240,  241,
      242,  238,  250,  243,  244,  251,  252,  245,  246,  253,
      254,  255,  247,  256,  248,  249,  257,  258,  259,  260,
      261,  262,  263,  264,  265,  266,  250,  267,  268,  251,
      252,  269,  270,  253,  254,  255,  271,  256,  272,  273,

      257,  258,  259,  260,  261,  262,  263,  264,  265,  266,
      274,  267,  268,  275,  276,  269,  270,  277,  279,  280,
      271,  281,  272,  273,  282,  283,  284,  285,  286,  287,
      288,  289,  290,  291,  274,  292,  293,  275,  276,  294,
      295,  277,  279,  280,  296,  281,  297,  298,  282,  283,
      284,  285,  286,  287,  288,  289,  290,  291,  299,  292,
      293,  300,  301,  294,  295,  302,  303,  304,  296,  305,
      297,  298,  306,  307,  308,  309,  310,  313,  311,  314,
      315,  316,  299,  312,  317,  300,  301,  318,  319,  302,
      303,  304,  320,  305,  321,  322,  306,  307,  308,  309,

      310,  313,  311,  314,  315,  316,  323,  312,  317,  324,
      326,  318,  319,  327,  328,  329,  320,  330,  321,  322,
      331,  332,  333,  334,  335,  336,  337,  338,  339,  340,
      323,  341,  341,  324,  326,  341,  341,  327,  328,  329,
      341,  330,  341,  341,  331,  332,  333,  334,  335,  336,
      337,  338,  339,  340,   43,   43,   43,   43,   43,   43,
       43,   46,   46,   46,   46,   46,   46,   46,   55,   55,
       58,   58,   65,   65,  341,   65,   65,   65,   65,   98,
       98,   98,   98,  341,   98,   98,  100,  100,  100,  341,
      100,  100,  100,  106,  341,  341,  106,  106,  106,  106,

        7,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341
    } ;

static yyconst flex_int16_t yy_chk[772] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,    9,    9,   10,   10,  349,   21,
       12,   21,   21,   21,   27,   28,   29,   30,   28,   31,
      313,   48,   12,   37,   31,   29,   31,   33,   32,   31,

       12,   33,   12,  254,   12,   32,   33,   39,   27,   28,
       29,   30,   28,   31,    5,    6,   12,   37,   31,   29,
       31,   33,   32,   31,   12,   33,   12,   34,  190,   32,
       33,   39,   34,   48,  185,    3,    4,   22,   35,   35,
       22,   36,   40,   36,   38,   22,   41,   42,   42,   60,
       38,   34,   22,  176,   22,  103,   34,   22,   38,   49,
       49,   22,   35,   35,   22,   36,   40,   36,   38,   22,
       41,   42,   42,   60,   38,   50,   22,   59,   22,   51,
       51,   22,   38,   53,   57,   59,   57,   57,   57,   61,
       62,   63,   53,   64,   53,   68,   53,   53,   53,   53,

       69,   59,   70,   71,   72,   73,   74,   53,   75,   59,
       76,   77,   45,   61,   62,   63,   53,   64,   53,   68,
       53,   53,   53,   53,   69,   81,   70,   71,   72,   73,
       74,   80,   75,   82,   76,   77,   80,   83,   84,   85,
       87,   88,   89,   90,   91,   89,   88,   92,   94,   81,
       95,   96,   97,  104,  104,   80,  107,   82,  108,  109,
       80,   83,   84,   85,   87,   88,   89,   90,   91,   89,
       88,   92,   94,  110,   95,   96,   97,  111,  112,  113,
      107,  114,  108,  109,  115,  116,  117,  118,  119,  120,
      122,  111,  123,  125,   26,  127,  128,  110,   24,  129,

      130,  111,  112,  113,  131,  114,  124,  133,  115,  116,
      117,  118,  119,  120,  122,  111,  123,  125,  124,  127,
      128,  134,  124,  129,  130,  137,  138,  139,  131,  140,
      124,  133,  141,  142,  143,  144,  145,  146,  147,  148,
      149,  150,  124,  151,  152,  134,  124,  153,  154,  137,
      138,  139,  155,  140,  156,  157,  141,  142,  143,  144,
      145,  146,  147,  148,  149,  150,  158,  151,  152,  159,
      160,  153,  154,  161,  162,  163,  155,  164,  156,  157,
      165,  166,  167,  168,  169,  170,  172,  174,  175,  179,
      158,  180,  181,  159,  160,  182,  183,  161,  162,  163,

      186,  164,  187,  188,  165,  166,  167,  168,  169,  170,
      172,  174,  175,  179,  189,  180,  181,  191,  192,  182,
      183,  193,  194,  195,  186,  196,  187,  188,  197,  199,
      200,  201,  202,  203,  205,  207,  208,  202,  189,  209,
      211,  191,  192,  212,  213,  193,  194,  195,  214,  196,
      215,  216,  197,  199,  200,  201,  202,  203,  205,  207,
      208,  202,  219,  209,  211,  220,  221,  212,  213,  222,
      224,  226,  214,  227,  215,  216,  228,  229,  231,  232,
      233,  234,  235,  236,  237,  238,  219,  239,  240,  220,
      221,  241,  242,  222,  224,  226,  243,  227,  244,  246,

      228,  229,  231,  232,  233,  234,  235,  236,  237,  238,
      248,  239,  240,  249,  252,  241,  242,  253,  255,  256,
      243,  257,  244,  246,  258,  259,  260,  262,  263,  264,
      265,  266,  269,  270,  248,  271,  274,  249,  252,  275,
      276,  253,  255,  256,  277,  257,  278,  279,  258,  259,
      260,  262,  263,  264,  265,  266,  269,  270,  280,  271,
      274,  281,  282,  275,  276,  285,  286,  287,  277,  289,
      278,  279,  290,  292,  293,  295,  296,  298,  297,  299,
      300,  303,  280,  297,  304,  281,  282,  306,  307,  285,
      286,  287,  308,  289,  309,  310,  290,  292,  293,  295,

      296,  298,  297,  299,  300,  303,  311,  297,  304,  312,
      314,  306,  307,  316,  317,  318,  308,  319,  309,  310,
      320,  324,  325,  328,  330,  333,  334,  336,  337,  338,
      311,    7,    0,  312,  314,    0,    0,  316,  317,  318,
        0,  319,    0,    0,  320,  324,  325,  328,  330,  333,
      334,  336,  337,  338,  342,  342,  342,  342,  342,  342,
      342,  343,  343,  343,  343,  343,  343,  343,  344,  344,
      345,  345,  346,  346,    0,  346,  346,  346,  346,  347,
      347,  347,  347,    0,  347,  347,  348,  348,  348,    0,
      348,  348,  348,  350,    0,    0,  350,  350,  350,  350,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.flex"
#line 2 "lexer.flex"

#include <string.h>
#include "parser.tab.h"

int my_powah(int base, int n)
{
    int result = 1;
    for (int i = 0; i < n; i++)
        result *= base;
    return result;
}

int nondec2dec(char * string, int base)
{
    int result = 0;
    size_t length = strlen(string);
    for (size_t i = 0; i < length; i++)
    {
        char cur = string[length - i - 1];
        int tmp = 0;
        switch (cur)
        {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            tmp = (int)cur - 0x30;
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
            tmp = (int)cur - ('A' - 0xA);
            break;
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
            tmp = (int)cur - ('a' - 0xA);
            break;
        default:
            tmp = 0;
        }
        result += tmp * my_powah(base, i);
    }
    return result;
}

void buffer_output(char * title, char * buf, unsigned int len)
{
    printf("%s", title);
    for (unsigned int i = 0; i < len; i++)
        printf("%c", buf[i]);
    printf("\n");
}



#line 808 "lexer.c"

#define INITIAL 0
#define COMMENT_ML 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 86 "lexer.flex"



char            buffer[8 * 1024];   // For storing strings, comments etc.
unsigned int    buffer_length = 0;  // Length of the buffer.


#line 1000 "lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 342 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 341 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 93 "lexer.flex"
{
    // Multiline comment beginning.
    buffer_length = 0;
    BEGIN(COMMENT_ML);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 98 "lexer.flex"
{
    // String constant beginning.
    buffer_length = 0;
    BEGIN(STRING);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 103 "lexer.flex"
{
    // Singleline comment.
    strcpy(buffer, yytext + 1);
    buffer_length = strlen(yytext + 1);
    buffer_output("Comment:                   ", buffer, buffer_length);
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 109 "lexer.flex"
{
    // Whitespaces.
    //printf("Skipping whitespace\n");
    //printf("Whitespace:  %s\n", yytext);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 114 "lexer.flex"
{
    // Opening parenthesis.
    printf("Opening paren:             %s\n", yytext);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 118 "lexer.flex"
{
    // Closing parenthesis.
    printf("Closing paren:             %s\n", yytext);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 122 "lexer.flex"
{
    // Operator: addition.
    printf("Operator add:              %s\n", yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 126 "lexer.flex"
{
    // Operator: subtraction.
    printf("Operator sub:              %s\n", yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 130 "lexer.flex"
{
    // Operator: multiplication.
    printf("Operator mult:             %s\n", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 134 "lexer.flex"
{
    // Operator: division.
    printf("Operator div:              %s\n", yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 138 "lexer.flex"
{
    // Operator: greater.
    printf("Operator greater:          %s\n", yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 142 "lexer.flex"
{
    // Operator: greater or equal.
    printf("Operator greater or equal: %s\n", yytext);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "lexer.flex"
{
    // Operator: less.
    printf("Operator less:             %s\n", yytext);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 150 "lexer.flex"
{
    // Operator: less or equal.
    printf("Operator less or equal:    %s\n", yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 154 "lexer.flex"
{
    // Operator: equal.
    printf("Operator equal:            %s\n", yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 158 "lexer.flex"
{
    // Operator: and.
    printf("Operator and:              %s\n", yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 162 "lexer.flex"
{
    // Operator: or.
    printf("Operator or:               %s\n", yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 166 "lexer.flex"
{
    // Operator: not.
    printf("Operator not:              %s\n", yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 170 "lexer.flex"
{
    // Boolean constant - true.
    printf("Boolean constant - true:   %s\n", yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 174 "lexer.flex"
{
    // Boolean constant - false.
    printf("Boolean constant - false:  %s\n", yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 178 "lexer.flex"
{
    // Numeric constant - binary.
    int value = nondec2dec(yytext + 2, 2);
    printf("Numeric constant - bin:    %d\n", value);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 183 "lexer.flex"
{
    // Numeric constant - octal.
    int value = nondec2dec(yytext + 2, 8);
    printf("Numeric constant - oct:    %d\n", value);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 188 "lexer.flex"
{
    // Numeric constant.
    if (yytext[yyleng - 1] == '.')
        yytext[yyleng - 1] = '\0';
    int value = nondec2dec(yytext, 10);
    printf("Numeric constant - dec:    %d\n", value);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 195 "lexer.flex"
{
    // Numeric constant - hexadecimal.
    int value = nondec2dec(yytext + 2, 16);
    printf("Numeric constant - hex:    %d\n", value);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 200 "lexer.flex"
{
    // Character constant.
    printf("Character constant:        %s\n", yytext + 2);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 204 "lexer.flex"
{
    // Character constant - whitespace.
    // TODO: convert to a real character.
    printf("Character constant:        %s\n", yytext + 2);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 209 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 212 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 215 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 218 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 221 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 224 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 227 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 230 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 233 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 236 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 239 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 242 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 245 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 248 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 251 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 254 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 257 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 260 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 263 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 266 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 269 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 272 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 275 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 278 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 281 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 284 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 287 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 290 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 293 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 296 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 299 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 302 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 305 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 308 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 311 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 314 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 317 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 320 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 323 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 326 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 329 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 332 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 335 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 338 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 341 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 344 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 347 "lexer.flex"
{
    printf("Symbol:                    %s\n", yytext);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 350 "lexer.flex"
{
    printf("UNEXPECTED CHARACTER:      %s\n", yytext);
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 353 "lexer.flex"
{
    // Multiline comment body: any character.
    buffer[buffer_length++] = yytext[0];
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 357 "lexer.flex"
{
    // Multiline comment body: any character.
    buffer[buffer_length++] = yytext[0];
}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 361 "lexer.flex"
{
    // Multiline comment body: any character.
    for (int i = 0; i < yyleng; i++)
        buffer[buffer_length++] = yytext[i];
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 366 "lexer.flex"
{
    // Multiline comment ending.
    buffer_output("Comment:                   ", buffer, buffer_length);
    buffer_length = 0;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(COMMENT_ML):
#line 372 "lexer.flex"
{
    puts("ERROR: UNCLOSED COMMENT");
    yyterminate();
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 376 "lexer.flex"
{
    // String constant body: escaped quote character.
    buffer[buffer_length++] = '"';
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 380 "lexer.flex"
{
    // String constant body: escaped slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 384 "lexer.flex"
{
    // String constant body: non-quote, non-slash characters.
    for (int i = 0; i < yyleng; i++)
        buffer[buffer_length++] = yytext[i];
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 389 "lexer.flex"
{
    // String constant body: unrecognized slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 393 "lexer.flex"
{
    // String constant ending.
    buffer_output("String constant:           ", buffer, buffer_length);
    buffer_length = 0;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 399 "lexer.flex"
{
    puts("ERROR: UNCLOSED STRING CONSTANT");
    yyterminate();
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 404 "lexer.flex"
ECHO;
	YY_BREAK
#line 1735 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 342 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 342 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 341);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 404 "lexer.flex"



