#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[328] =
    {   0,
        0,    0,    0,    0,    0,    0,   82,   71,    4,    4,
        2,   71,   70,   59,    5,    6,    9,    7,    8,   10,
       23,   71,    3,   13,   15,   11,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   19,   70,
       70,   74,   73,   72,   78,   80,   79,    4,    0,    0,
        0,    0,    1,   70,   23,   23,   69,   69,   69,   69,
       69,   69,   69,    3,   14,   12,   70,   70,   70,   70,
       30,   70,   70,   70,   70,   70,   35,   29,   70,   70,
       70,   70,   70,   70,   17,   70,   70,   70,   70,   70,
       70,   32,   70,   70,   70,   74,   75,   78,   76,   77,

       21,   22,   24,   25,   25,   25,   25,   25,   25,   25,
       25,   69,   69,   69,   69,   69,   69,   69,   16,   70,
       70,   70,   43,   70,   28,   70,   70,   70,   39,   70,
       70,   20,   18,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,    0,    0,    0,    0,    0,    0,
        0,    0,   69,   69,   69,   69,   69,   69,   69,   70,
       70,   70,   70,   70,   70,   47,   31,   70,   70,   44,
       27,   54,   70,   70,   70,   70,   38,   70,   70,   70,
       70,   70,    0,    0,    0,    0,    0,    0,    0,   26,
       69,   69,   69,   69,   69,   67,   69,   55,   70,   70,

       70,   52,   70,   70,   70,   70,   70,   60,   34,   70,
       70,   70,   70,   33,   70,    0,    0,    0,   26,    0,
        0,    0,   69,   69,   69,   69,   69,   69,   69,   70,
       70,   70,   37,   70,   46,   70,   70,   49,   70,   70,
       40,   70,    0,    0,    0,    0,    0,   26,   69,   69,
       69,   69,   69,   62,   63,   70,   70,   70,   57,   70,
       70,   70,   70,   70,   70,    0,    0,    0,   26,   26,
       69,   69,   69,   65,   69,   70,   58,   70,   70,   48,
       70,   70,   70,   70,    0,    0,   26,   64,   69,   69,
       61,   70,   70,   70,   70,   70,   70,   70,   70,    0,

       26,   69,   69,   70,   70,   70,   53,   50,   42,   70,
       70,   26,   66,   69,   51,   70,   45,   41,   70,   69,
       36,   70,   69,   70,   68,   56,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    6,    6,    7,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,    1,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,    6,   32,   33,   34,   35,   36,   37,
        6,   38,   39,   40,   41,   42,   43,   44,   45,    6,
        1,   46,    1,    6,    6,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,    6,   56,   57,   58,   59,
       60,   61,    6,   62,   63,   64,   65,   66,   67,   68,
       69,    6,    1,   70,    1,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    2,    3,    4,    5,    6,    1,    1,    1,    6,
        6,    6,    6,    6,    7,    7,    7,    1,    1,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    4,    7,    7,    7,    7,
        7,    7,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    5
    } ;

static yyconst flex_int16_t yy_base[337] =
    {   0,
        0,    0,   66,   67,   69,   70,  642,  668,   73,   75,
      668,   57,    0,  668,  668,  668,    0,    0,    0,    0,
       67,  115,    0,  597,    0,  595,   50,   53,   60,   55,
       59,   71,   71,   97,  102,  106,   67,  118,   72,  116,
      117,    0,  668,  608,    0,  668,   88,  147,  595,  145,
        0,  160,  668,    0,    0,  172,    0,  153,  120,  146,
      163,  146,  154,    0,    0,    0,  168,  160,  166,  175,
        0,  164,  171,  169,  173,  176,    0,    0,  194,  173,
      177,  193,  192,  211,    0,  200,  209,  207,  202,  207,
      220,    0,  221,  216,  208,    0,  668,    0,  668,  668,

      161,  158,    0,  668,  226,  220,  225,  231,  233,  218,
      234,  234,  228,  252,  249,  259,  249,  256,    0,  249,
      264,  266,    0,  264,    0,  258,  268,  265,    0,  255,
      259,    0,    0,  262,  268,  265,  273,  269,  281,  282,
      286,  288,  297,  304,  310,  301,  294,  309,  299,  316,
      318,  318,  316,  308,  304,  307,  322,  323,  311,  326,
      332,  323,  334,  335,  350,    0,    0,  353,  338,  142,
        0,    0,  342,  343,  349,  343,    0,  123,  346,  351,
      361,  117,  357,  363,  358,  365,  352,  359,  371,  668,
      359,  374,  367,  398,  376,    0,  377,    0,  365,  395,

      386,    0,  392,  398,  402,  400,  403,    0,    0,  408,
      394,  406,  400,    0,  403,  401,  413,  412,  668,  406,
      405,  420,  410,  428,  425,  415,  430,  431,  434,  447,
      439,  456,    0,  447,    0,  454,  446,    0,  460,  444,
       92,  448,  449,  460,  453,  454,  451,  668,  456,  454,
      460,  468,  461,    0,    0,  465,  462,  480,    0,  482,
      485,  489,  485,  490,  501,  506,  503,  504,  668,  668,
      494,  502,  494,    0,  501,  513,    0,  510,  510,    0,
      499,  502,  507,  510,  522,  523,  668,    0,  526,  542,
        0,  528,  530,  534,  548,  549,  540,  539,   79,  552,

      668,  545,  541,  555,  556,  554,    0,    0,    0,  555,
      559,  668,    0,  557,    0,  552,    0,    0,  560,  557,
        0,  562,  561,  570,    0,    0,  668,  621,  628,  630,
      632,  639,  646,  653,   72,  660
    } ;

static yyconst flex_int16_t yy_def[337] =
    {   0,
      327,    1,  328,  328,  329,  329,  327,  327,  327,  327,
      327,  327,  330,  327,  327,  327,  330,  330,  330,  330,
      330,  331,  332,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  333,  327,  327,  334,  327,  327,  327,  327,  327,
      335,  336,  327,  330,  330,  330,  331,  331,  331,  331,
      331,  331,  331,  332,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  333,  327,  334,  327,  327,

      327,  327,  335,  327,  327,  327,  327,  327,  327,  327,
      327,  331,  331,  331,  331,  331,  331,  331,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  327,  327,  327,  327,  327,  327,
      327,  327,  331,  331,  331,  331,  331,  331,  331,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  327,  327,  327,  327,  327,  327,  327,  327,
      331,  331,  331,  331,  331,  331,  331,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  327,  327,  327,  327,  327,
      327,  327,  331,  331,  331,  331,  331,  331,  331,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  327,  327,  327,  327,  327,  327,  331,  331,
      331,  331,  331,  331,  331,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  327,  327,  327,  327,  327,
      331,  331,  331,  331,  331,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  327,  327,  327,  331,  331,  331,
      331,  330,  330,  330,  330,  330,  330,  330,  330,  327,

      327,  331,  331,  330,  330,  330,  330,  330,  330,  330,
      330,  327,  331,  331,  330,  330,  330,  330,  330,  331,
      330,  330,  331,  330,  331,  330,    0,  327,  327,  327,
      327,  327,  327,  327,  327,  327
    } ;

static yyconst flex_int16_t yy_nxt[739] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   13,   20,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   13,   28,   29,   30,   31,   13,   13,
       32,   13,   33,   13,   34,   35,   36,   37,   38,   39,
       13,   40,   41,   13,   13,    8,   27,   13,   28,   29,
       30,   31,   13,   13,   32,   13,   33,   13,   34,   35,
       36,   37,   38,   39,   13,   40,   41,   13,   13,    8,
       43,   43,   46,   46,   48,   48,   48,   48,  103,   55,
       49,   56,   56,   56,   67,   68,   70,   72,   69,   73,
      311,   99,   50,   88,   74,   71,   75,   79,   77,   76,

       51,   80,   52,  264,   49,   78,   81,   92,   67,   68,
       70,   72,   69,   73,   47,   47,   50,   88,   74,   71,
       75,   79,   77,   76,   51,   80,   53,   82,  215,   78,
       81,   92,   83,  100,  211,   44,   44,   58,   84,   85,
       59,   86,   93,   87,   89,   60,   94,   95,   48,   48,
       90,   82,   61,  206,   62,  114,   83,   63,   91,  102,
      102,   58,   84,   85,   59,   86,   93,   87,   89,   60,
       94,   95,  102,  102,   90,  101,   61,  112,   62,  114,
      115,   63,   91,  105,   55,  113,   56,   56,   56,  116,
      117,  118,  106,  119,  107,  120,  108,  109,  110,  111,

      121,  112,  122,  123,  115,  124,  125,  105,  126,  113,
      127,  130,  131,  116,  117,  118,  106,  119,  107,  120,
      108,  109,  110,  111,  121,  132,  122,  123,  128,  124,
      125,  133,  126,  129,  127,  130,  131,  134,  135,  136,
      138,  139,  140,  141,  137,  142,  143,  144,  145,  132,
      146,  147,  128,  148,  151,  133,  152,  129,  153,  149,
      154,  134,  135,  136,  138,  139,  140,  141,  137,  142,
      143,  144,  145,  150,  146,  147,  155,  148,  151,  156,
      152,  157,  153,  149,  154,  158,  159,  160,  161,  166,
      162,  167,  168,  169,  170,  171,  172,  150,  173,  174,

      155,  175,  163,  156,  176,  157,  164,  165,  177,  158,
      159,  160,  161,  166,  162,  167,  168,  169,  170,  171,
      172,  178,  173,  174,  179,  175,  163,  180,  176,  181,
      164,  165,  177,  182,  183,  184,  185,  186,  187,  188,
      189,  190,  191,  192,  193,  178,  194,  195,  179,  196,
      197,  180,  198,  181,  199,  200,  201,  182,  183,  184,
      185,  186,  187,  188,  189,  190,  191,  192,  193,  202,
      194,  195,  203,  196,  197,  204,  198,  205,  199,  200,
      201,  207,  208,  209,  210,  212,  213,  214,  216,  217,
      218,  219,  220,  202,  221,  222,  203,  223,  224,  204,

      225,  205,  228,  229,  230,  207,  208,  209,  210,  212,
      213,  214,  216,  217,  218,  219,  220,  231,  221,  222,
      226,  223,  224,  232,  225,  227,  228,  229,  230,  233,
      234,  235,  236,  237,  238,  239,  240,  241,  242,  243,
      244,  231,  245,  246,  226,  247,  248,  232,  249,  227,
      250,  251,  252,  233,  234,  235,  236,  237,  238,  239,
      240,  241,  242,  243,  244,  253,  245,  246,  254,  247,
      248,  255,  249,  256,  250,  251,  252,  257,  258,  259,
      260,  261,  262,  263,  265,  266,  267,  268,  269,  253,
      270,  271,  254,  272,  273,  255,  274,  256,  275,  276,

      277,  257,  258,  259,  260,  261,  262,  263,  265,  266,
      267,  268,  269,  278,  270,  271,  279,  272,  273,  280,
      274,  281,  275,  276,  277,  282,  283,  284,  285,  286,
      287,  288,  289,  290,  291,  292,  293,  278,  294,  295,
      279,  296,  297,  280,  299,  281,  300,  298,  301,  282,
      283,  284,  285,  286,  287,  288,  289,  290,  291,  292,
      293,  302,  294,  295,  303,  296,  297,  304,  299,  305,
      300,  298,  301,  306,  307,  308,  309,  310,  312,  313,
      314,  315,  316,  317,  318,  302,  319,  320,  303,  321,
      322,  304,  323,  305,  324,  325,  326,  306,  307,  308,

      309,  310,  312,  313,  314,  315,  316,  317,  318,  101,
      319,  320,   97,  321,  322,   66,  323,   65,  324,  325,
      326,   42,   42,   42,   42,   42,   42,   42,   45,   45,
       45,   45,   45,   45,   45,   54,   54,   57,   57,   64,
       64,  327,   64,   64,   64,   64,   96,   96,   96,   96,
      327,   96,   96,   98,   98,   98,  327,   98,   98,   98,
      104,  327,  327,  104,  104,  104,  104,    7,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327
    } ;

static yyconst flex_int16_t yy_chk[739] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,    9,    9,   10,   10,  335,   21,
       12,   21,   21,   21,   27,   28,   29,   30,   28,   31,
      299,   47,   12,   37,   31,   29,   31,   33,   32,   31,

       12,   33,   12,  241,   12,   32,   33,   39,   27,   28,
       29,   30,   28,   31,    5,    6,   12,   37,   31,   29,
       31,   33,   32,   31,   12,   33,   12,   34,  182,   32,
       33,   39,   34,   47,  178,    3,    4,   22,   35,   35,
       22,   36,   40,   36,   38,   22,   41,   41,   48,   48,
       38,   34,   22,  170,   22,   59,   34,   22,   38,   50,
       50,   22,   35,   35,   22,   36,   40,   36,   38,   22,
       41,   41,  102,  102,   38,  101,   22,   58,   22,   59,
       60,   22,   38,   52,   56,   58,   56,   56,   56,   61,
       62,   63,   52,   67,   52,   68,   52,   52,   52,   52,

       69,   58,   70,   72,   60,   73,   74,   52,   75,   58,
       76,   80,   81,   61,   62,   63,   52,   67,   52,   68,
       52,   52,   52,   52,   69,   82,   70,   72,   79,   73,
       74,   83,   75,   79,   76,   80,   81,   84,   86,   87,
       88,   89,   90,   91,   87,   93,   94,   95,  105,   82,
      106,  107,   79,  108,  110,   83,  111,   79,  112,  109,
      113,   84,   86,   87,   88,   89,   90,   91,   87,   93,
       94,   95,  105,  109,  106,  107,  114,  108,  110,  115,
      111,  116,  112,  109,  113,  117,  118,  120,  121,  124,
      122,  126,  127,  128,  130,  131,  134,  109,  135,  136,

      114,  137,  122,  115,  138,  116,  122,  122,  139,  117,
      118,  120,  121,  124,  122,  126,  127,  128,  130,  131,
      134,  140,  135,  136,  141,  137,  122,  142,  138,  143,
      122,  122,  139,  144,  145,  146,  147,  148,  149,  150,
      151,  152,  153,  154,  155,  140,  156,  157,  141,  158,
      159,  142,  160,  143,  161,  162,  163,  144,  145,  146,
      147,  148,  149,  150,  151,  152,  153,  154,  155,  164,
      156,  157,  165,  158,  159,  168,  160,  169,  161,  162,
      163,  173,  174,  175,  176,  179,  180,  181,  183,  184,
      185,  186,  187,  164,  188,  189,  165,  191,  192,  168,

      193,  169,  195,  197,  199,  173,  174,  175,  176,  179,
      180,  181,  183,  184,  185,  186,  187,  200,  188,  189,
      194,  191,  192,  201,  193,  194,  195,  197,  199,  203,
      204,  205,  206,  207,  210,  211,  212,  213,  215,  216,
      217,  200,  218,  220,  194,  221,  222,  201,  223,  194,
      224,  225,  226,  203,  204,  205,  206,  207,  210,  211,
      212,  213,  215,  216,  217,  227,  218,  220,  228,  221,
      222,  229,  223,  230,  224,  225,  226,  231,  232,  234,
      236,  237,  239,  240,  242,  243,  244,  245,  246,  227,
      247,  249,  228,  250,  251,  229,  252,  230,  253,  256,

      257,  231,  232,  234,  236,  237,  239,  240,  242,  243,
      244,  245,  246,  258,  247,  249,  260,  250,  251,  261,
      252,  262,  253,  256,  257,  263,  264,  265,  266,  267,
      268,  271,  272,  273,  275,  276,  278,  258,  279,  281,
      260,  282,  283,  261,  284,  262,  285,  283,  286,  263,
      264,  265,  266,  267,  268,  271,  272,  273,  275,  276,
      278,  289,  279,  281,  290,  282,  283,  292,  284,  293,
      285,  283,  286,  294,  295,  296,  297,  298,  300,  302,
      303,  304,  305,  306,  310,  289,  311,  314,  290,  316,
      319,  292,  320,  293,  322,  323,  324,  294,  295,  296,

      297,  298,  300,  302,  303,  304,  305,  306,  310,   49,
      311,  314,   44,  316,  319,   26,  320,   24,  322,  323,
      324,  328,  328,  328,  328,  328,  328,  328,  329,  329,
      329,  329,  329,  329,  329,  330,  330,  331,  331,  332,
      332,    7,  332,  332,  332,  332,  333,  333,  333,  333,
        0,  333,  333,  334,  334,  334,    0,  334,  334,  334,
      336,    0,    0,  336,  336,  336,  336,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.flex"
#line 2 "lexer.flex"

#include <string.h>
#include <ctype.h>
#include "parser.tab.h"

int my_powah(int base, int n)
{
    int result = 1;
    for (int i = 0; i < n; i++)
        result *= base;
    return result;
}

int nondec2dec(char * string, int base)
{
    int result = 0;
    size_t length = strlen(string);
    for (size_t i = 0; i < length; i++)
    {
        char cur = string[length - i - 1];
        int tmp = 0;
        switch (cur)
        {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            tmp = (int)cur - 0x30;
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
            tmp = (int)cur - ('A' - 0xA);
            break;
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
            tmp = (int)cur - ('a' - 0xA);
            break;
        default:
            tmp = 0;
        }
        result += tmp * my_powah(base, i);
    }
    return result;
}

void store_function_id() {
    yylval.semantic_id = (char *)malloc(sizeof(char) * (yyleng + 1));
    strcpy(yylval.semantic_id, yytext);
    for (size_t i = 0; i < yyleng; i++)
        yylval.semantic_id[i] = tolower(yylval.semantic_id[i]);
}



#line 796 "lexer.c"

#define INITIAL 0
#define COMMENT_ML_ST 1
#define STRING_ST 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 86 "lexer.flex"



char            buffer[8 * 1024];   // For storing strings, comments etc.
unsigned int    buffer_length = 0;  // Length of the buffer.


#line 988 "lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 328 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 327 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 93 "lexer.flex"
{
    // Multiline comment beginning.
    BEGIN(COMMENT_ML_ST);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "lexer.flex"
{
    // String constant beginning.
    buffer_length = 0;
    BEGIN(STRING_ST);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 102 "lexer.flex"
{
    // Singleline comment, do nothing.
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 105 "lexer.flex"
{
    // Whitespaces, do nothing.
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "lexer.flex"
{
    // Opening parenthesis.
    return (unsigned char)'(';
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 112 "lexer.flex"
{
    // Closing parenthesis.
    return (unsigned char)')';
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "lexer.flex"
{
    // Operator: addition.
    store_function_id();
    return ID;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "lexer.flex"
{
    // Operator: subtraction.
    store_function_id();
    return ID;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 126 "lexer.flex"
{
    // Operator: multiplication.
     store_function_id();
    return ID;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "lexer.flex"
{
    // Operator: division.
    store_function_id();
    return ID;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "lexer.flex"
{
    // Operator: greater.
    store_function_id();
    return ID;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 141 "lexer.flex"
{
    // Operator: greater or equal.
    store_function_id();
    return ID;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "lexer.flex"
{
    // Operator: less.
    store_function_id();
    return ID;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 151 "lexer.flex"
{
    // Operator: less or equal.
    store_function_id();
    return ID;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 156 "lexer.flex"
{
    // Operator: equal.
    store_function_id();
    return ID;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 161 "lexer.flex"
{
    // Operator: and.
    store_function_id();
    return ID;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 166 "lexer.flex"
{
    // Operator: or.
    store_function_id();
    return ID;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 171 "lexer.flex"
{
    // Operator: not.
    store_function_id();
    return ID;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 176 "lexer.flex"
{
    // Boolean constant - true.
    yylval.semantic_bool = 1;
    return BOOL;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 181 "lexer.flex"
{
    // Boolean constant - false.
    yylval.semantic_bool = 0;
    return BOOL;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 186 "lexer.flex"
{
    // Numeric constant - binary.
    yylval.semantic_int = nondec2dec(yytext + 2, 2);
    return INT;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 191 "lexer.flex"
{
    // Numeric constant - octal.
    yylval.semantic_int = nondec2dec(yytext + 2, 8);
    return INT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 196 "lexer.flex"
{
    // Numeric constant.
    if (yytext[yyleng - 1] == '.')
        yytext[yyleng - 1] = '\0';
    yylval.semantic_int = nondec2dec(yytext, 10);
    return INT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 203 "lexer.flex"
{
    // Numeric constant - hexadecimal.
    yylval.semantic_int = nondec2dec(yytext + 2, 16);
    return INT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 208 "lexer.flex"
{
    // Character constant.
    yylval.semantic_char = yytext[2];
    return CHAR;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 213 "lexer.flex"
{
    // Character constant - whitespace.
    yylval.semantic_char = 'q'; // TODO: convert to a real character.
    return CHAR;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 218 "lexer.flex"
{
    return LOOP;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 221 "lexer.flex"
{
    return FOR;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 224 "lexer.flex"
{
    return IN;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 227 "lexer.flex"
{
    return DO;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 230 "lexer.flex"
{
    return FROM;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 233 "lexer.flex"
{
    return TO;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 236 "lexer.flex"
{
    return WHILE;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 239 "lexer.flex"
{
    return PROGN;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 242 "lexer.flex"
{
    return IF;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 245 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 249 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 253 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 257 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 261 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 265 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 269 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 273 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 277 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 281 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 285 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 289 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 293 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 297 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 301 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 305 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 309 "lexer.flex"
{
    return DEFUN;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 312 "lexer.flex"
{
    return SLOTVALUE;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 315 "lexer.flex"
{
    return OPEN;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 318 "lexer.flex"
{
    return CLOSE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 321 "lexer.flex"
{
    return WITHOPENFILE;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 324 "lexer.flex"
{
    return FUNCALL;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 327 "lexer.flex"
{
    return DEFCLASS;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 330 "lexer.flex"
{
    return (unsigned char)'\'';
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 333 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 337 "lexer.flex"
{
    return INITFORM;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 340 "lexer.flex"
{
    return READER;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 343 "lexer.flex"
{
    return WRITER;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 346 "lexer.flex"
{
    return ACCESSOR;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 349 "lexer.flex"
{
    return INITARG;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 352 "lexer.flex"
{
    return ALLOCATION;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 355 "lexer.flex"
{
    return TYPE;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 358 "lexer.flex"
{
    return DOCUMENTATION;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 361 "lexer.flex"
{
    store_function_id();
    return ID;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 365 "lexer.flex"
{
    // User-defined symbol.
    store_function_id();
    return ID;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 370 "lexer.flex"
{
    printf("UNEXPECTED CHARACTER:      %s\n", yytext);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 373 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 376 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 379 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 382 "lexer.flex"
{
    // Multiline comment ending.
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(COMMENT_ML_ST):
#line 386 "lexer.flex"
{
    puts("ERROR: UNCLOSED COMMENT");
    yyterminate();
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 390 "lexer.flex"
{
    // String constant body: escaped quote character.
    buffer[buffer_length++] = '"';
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 394 "lexer.flex"
{
    // String constant body: escaped slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 398 "lexer.flex"
{
    // String constant body: non-quote, non-slash characters.
    for (int i = 0; i < yyleng; i++)
        buffer[buffer_length++] = yytext[i];
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 403 "lexer.flex"
{
    // String constant body: unrecognized slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 407 "lexer.flex"
{
    // String constant ending.
    yylval.semantic_string = (char *)malloc(sizeof(char) * (buffer_length + 1));
    strcpy(yylval.semantic_string, buffer);
    buffer_length = 0;
    BEGIN(INITIAL);
    return STRING;
}
	YY_BREAK
case YY_STATE_EOF(STRING_ST):
#line 415 "lexer.flex"
{
    puts("ERROR: UNCLOSED STRING CONSTANT");
    yyterminate();
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 420 "lexer.flex"
ECHO;
	YY_BREAK
#line 1727 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 328 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 328 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 327);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 420 "lexer.flex"



