#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[333] =
    {   0,
        0,    0,    0,    0,    0,    0,   83,   72,    4,    4,
        2,   72,   71,   60,    5,    6,    9,    7,    8,   10,
       23,   72,    3,   13,   15,   11,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   19,   71,
       71,   75,   74,   73,   79,   81,   80,    4,    0,    0,
        0,    0,    1,   71,   23,   23,   70,   70,   70,   70,
       70,   70,   70,    3,   14,   12,   71,   71,   71,   71,
       30,   71,   71,   71,   71,   71,   50,   29,   71,   71,
       71,   71,   71,   71,   17,   71,   71,   71,   71,   71,
       71,   32,   71,   71,   71,   75,   76,   79,   77,   78,

       21,   22,   24,   25,   25,   25,   25,   25,   25,   25,
       25,   70,   70,   70,   70,   70,   70,   70,   16,   71,
       71,   71,   71,   41,   71,   28,   71,   71,   71,   37,
       71,   71,   20,   18,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,    0,    0,    0,    0,    0,
        0,    0,    0,   70,   70,   70,   70,   70,   70,   70,
       71,   71,   71,   71,   71,   71,   45,   71,   31,   71,
       71,   42,   27,   54,   71,   71,   71,   71,   36,   71,
       71,   71,   71,   71,    0,    0,    0,    0,    0,    0,
        0,   26,   70,   70,   70,   70,   70,   68,   70,   55,

       71,   71,   71,   52,   71,   71,   71,   71,   71,   71,
       61,   34,   71,   71,   71,   71,   33,   71,    0,    0,
        0,   26,    0,    0,    0,   70,   70,   70,   70,   70,
       70,   70,   71,   71,   71,   71,   57,   71,   44,   71,
       71,   47,   71,   71,   38,   71,    0,    0,    0,    0,
        0,   26,   70,   70,   70,   70,   70,   63,   64,   71,
       71,   71,   51,   58,   71,   71,   71,   71,   71,   71,
        0,    0,    0,   26,   26,   70,   70,   70,   66,   70,
       71,   59,   71,   71,   46,   71,   71,   71,   71,    0,
        0,   26,   65,   70,   70,   62,   71,   71,   71,   71,

       71,   71,   71,   71,    0,   26,   70,   70,   71,   71,
       71,   53,   48,   40,   71,   71,   26,   67,   70,   49,
       71,   43,   39,   71,   70,   35,   71,   70,   71,   69,
       56,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    6,    6,    7,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,    1,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,    6,   32,   33,   34,   35,   36,   37,
        6,   38,   39,   40,   41,   42,   43,   44,   45,    6,
        1,   46,    1,    6,    6,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,    6,   56,   57,   58,   59,
       60,   61,    6,   62,   63,   64,   65,   66,   67,   68,
       69,    6,    1,   70,    1,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    2,    3,    4,    5,    6,    1,    1,    1,    6,
        6,    6,    6,    6,    7,    7,    7,    1,    1,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    4,    7,    7,    7,    7,
        7,    7,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    5
    } ;

static yyconst flex_int16_t yy_base[342] =
    {   0,
        0,    0,   66,   67,   69,   70,  627,  693,   73,   75,
      693,   57,    0,  693,  693,  693,    0,    0,    0,    0,
       67,  115,    0,  605,    0,  604,   50,   53,   60,   55,
       59,   71,   71,   97,  102,  106,   67,  118,   72,  116,
      117,    0,  693,  619,    0,  693,   88,  147,  608,  145,
        0,  160,  693,    0,    0,  172,    0,  153,  120,  146,
      163,  146,  154,    0,    0,    0,  168,  160,  166,  175,
      164,  166,  172,  171,  175,  177,    0,    0,  194,  174,
      190,  199,  198,  212,    0,  201,  210,  208,  203,  208,
      221,    0,  222,  217,  209,    0,  693,    0,  693,  693,

      161,  158,    0,  693,  228,  221,  227,  232,  233,  220,
      236,  236,  244,  255,  251,  263,  250,  257,    0,  250,
      265,  266,  261,    0,  267,  260,  261,  271,  268,    0,
      259,  263,    0,    0,  267,  274,  273,  280,  286,  297,
      288,  291,  294,  302,  306,  312,  303,  296,  311,  301,
      318,  320,  320,  318,  311,  307,  310,  325,  326,  315,
      329,  334,  337,  350,  341,  344,    0,  359,    0,  360,
      344,  142,    0,    0,  345,  346,  352,  346,    0,  123,
      349,  354,  364,  117,  360,  366,  362,  369,  357,  363,
      376,  693,  364,  379,  371,  398,  391,    0,  397,    0,

      390,  408,  394,    0,  406,  394,  402,  406,  404,  407,
        0,    0,  412,  398,  410,  405,    0,  408,  407,  419,
      418,  693,  413,  411,  426,  427,  446,  445,  436,  442,
      441,  442,  454,  443,  460,  445,    0,  452,    0,  459,
      451,    0,  465,  449,   92,  454,  455,  467,  460,  462,
      459,  693,  464,  461,  479,  488,  482,    0,    0,  487,
      487,  493,    0,    0,  493,  494,  497,  490,  495,  506,
      511,  508,  509,  693,  693,  499,  508,  500,    0,  508,
      520,    0,  518,  518,    0,  507,  509,  529,  527,  543,
      548,  693,    0,  539,  553,    0,  537,  538,  539,  553,

      554,  545,  544,   79,  557,  693,  550,  547,  561,  563,
      561,    0,    0,    0,  563,  567,  693,    0,  565,    0,
      559,    0,    0,  579,  577,    0,  583,  583,  595,    0,
        0,  693,  646,  653,  655,  657,  664,  671,  678,   72,
      685
    } ;

static yyconst flex_int16_t yy_def[342] =
    {   0,
      332,    1,  333,  333,  334,  334,  332,  332,  332,  332,
      332,  332,  335,  332,  332,  332,  335,  335,  335,  335,
      335,  336,  337,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  338,  332,  332,  339,  332,  332,  332,  332,  332,
      340,  341,  332,  335,  335,  335,  336,  336,  336,  336,
      336,  336,  336,  337,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  338,  332,  339,  332,  332,

      332,  332,  340,  332,  332,  332,  332,  332,  332,  332,
      332,  336,  336,  336,  336,  336,  336,  336,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  332,  332,  332,  332,  332,
      332,  332,  332,  336,  336,  336,  336,  336,  336,  336,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  332,  332,  332,  332,  332,  332,
      332,  332,  336,  336,  336,  336,  336,  336,  336,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  332,  332,
      332,  332,  332,  332,  332,  336,  336,  336,  336,  336,
      336,  336,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  332,  332,  332,  332,
      332,  332,  336,  336,  336,  336,  336,  336,  336,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      332,  332,  332,  332,  332,  336,  336,  336,  336,  336,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  332,
      332,  332,  336,  336,  336,  336,  335,  335,  335,  335,

      335,  335,  335,  335,  332,  332,  336,  336,  335,  335,
      335,  335,  335,  335,  335,  335,  332,  336,  336,  335,
      335,  335,  335,  335,  336,  335,  335,  336,  335,  336,
      335,    0,  332,  332,  332,  332,  332,  332,  332,  332,
      332
    } ;

static yyconst flex_int16_t yy_nxt[764] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   13,   20,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   13,   28,   29,   30,   31,   13,   13,
       32,   13,   33,   13,   34,   35,   36,   37,   38,   39,
       13,   40,   41,   13,   13,    8,   27,   13,   28,   29,
       30,   31,   13,   13,   32,   13,   33,   13,   34,   35,
       36,   37,   38,   39,   13,   40,   41,   13,   13,    8,
       43,   43,   46,   46,   48,   48,   48,   48,  103,   55,
       49,   56,   56,   56,   67,   68,   70,   72,   69,   73,
      316,   99,   50,   88,   74,   71,   75,   79,   77,   76,

       51,   80,   52,  269,   49,   78,   81,   92,   67,   68,
       70,   72,   69,   73,   47,   47,   50,   88,   74,   71,
       75,   79,   77,   76,   51,   80,   53,   82,  218,   78,
       81,   92,   83,  100,  214,   44,   44,   58,   84,   85,
       59,   86,   93,   87,   89,   60,   94,   95,   48,   48,
       90,   82,   61,  209,   62,  114,   83,   63,   91,  102,
      102,   58,   84,   85,   59,   86,   93,   87,   89,   60,
       94,   95,  102,  102,   90,  101,   61,  112,   62,  114,
      115,   63,   91,  105,   55,  113,   56,   56,   56,  116,
      117,  118,  106,  119,  107,  120,  108,  109,  110,  111,

      121,  112,  122,  123,  115,  124,  125,  105,  126,  113,
      127,  128,  131,  116,  117,  118,  106,  119,  107,  120,
      108,  109,  110,  111,  121,  132,  122,  123,  129,  124,
      125,  133,  126,  130,  127,  128,  131,  134,  135,  136,
      137,  139,  140,  141,  142,  138,  143,  144,  145,  132,
      146,  147,  129,  148,  149,  133,  152,  130,  153,  150,
      154,  134,  135,  136,  137,  139,  140,  141,  142,  138,
      143,  144,  145,  151,  146,  147,  155,  148,  149,  156,
      152,  157,  153,  150,  154,  158,  159,  160,  161,  162,
      163,  166,  167,  168,  169,  170,  171,  151,  172,  173,

      155,  174,  164,  156,  175,  157,  165,  176,  177,  158,
      159,  160,  161,  162,  163,  166,  167,  168,  169,  170,
      171,  178,  172,  173,  179,  174,  164,  180,  175,  181,
      165,  176,  177,  182,  183,  184,  185,  186,  187,  188,
      189,  190,  191,  192,  193,  178,  194,  195,  179,  196,
      197,  180,  198,  181,  199,  200,  201,  182,  183,  184,
      185,  186,  187,  188,  189,  190,  191,  192,  193,  202,
      194,  195,  203,  196,  197,  204,  198,  205,  199,  200,
      201,  206,  207,  208,  210,  211,  212,  213,  215,  216,
      217,  219,  220,  202,  221,  222,  203,  223,  224,  204,

      225,  205,  226,  227,  228,  206,  207,  208,  210,  211,
      212,  213,  215,  216,  217,  219,  220,  231,  221,  222,
      229,  223,  224,  232,  225,  230,  226,  227,  228,  233,
      234,  235,  236,  237,  238,  239,  240,  241,  242,  243,
      244,  231,  245,  246,  229,  247,  248,  232,  249,  230,
      250,  251,  252,  233,  234,  235,  236,  237,  238,  239,
      240,  241,  242,  243,  244,  253,  245,  246,  254,  247,
      248,  255,  249,  256,  250,  251,  252,  257,  258,  259,
      260,  261,  262,  263,  264,  265,  266,  267,  268,  253,
      270,  271,  254,  272,  273,  255,  274,  256,  275,  276,

      277,  257,  258,  259,  260,  261,  262,  263,  264,  265,
      266,  267,  268,  278,  270,  271,  279,  272,  273,  280,
      274,  281,  275,  276,  277,  282,  283,  284,  285,  286,
      287,  288,  289,  290,  291,  292,  293,  278,  294,  295,
      279,  296,  297,  280,  298,  281,  299,  300,  301,  282,
      283,  284,  285,  286,  287,  288,  289,  290,  291,  292,
      293,  304,  294,  295,  302,  296,  297,  305,  298,  303,
      299,  300,  301,  306,  307,  308,  309,  310,  311,  312,
      313,  314,  315,  317,  318,  304,  319,  320,  302,  321,
      322,  305,  323,  303,  324,  325,  326,  306,  307,  308,

      309,  310,  311,  312,  313,  314,  315,  317,  318,  327,
      319,  320,  328,  321,  322,  329,  323,  330,  324,  325,
      326,  331,  101,   97,   66,   65,  332,  332,  332,  332,
      332,  332,  332,  327,  332,  332,  328,  332,  332,  329,
      332,  330,  332,  332,  332,  331,   42,   42,   42,   42,
       42,   42,   42,   45,   45,   45,   45,   45,   45,   45,
       54,   54,   57,   57,   64,   64,  332,   64,   64,   64,
       64,   96,   96,   96,   96,  332,   96,   96,   98,   98,
       98,  332,   98,   98,   98,  104,  332,  332,  104,  104,
      104,  104,    7,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332
    } ;

static yyconst flex_int16_t yy_chk[764] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,    9,    9,   10,   10,  340,   21,
       12,   21,   21,   21,   27,   28,   29,   30,   28,   31,
      304,   47,   12,   37,   31,   29,   31,   33,   32,   31,

       12,   33,   12,  245,   12,   32,   33,   39,   27,   28,
       29,   30,   28,   31,    5,    6,   12,   37,   31,   29,
       31,   33,   32,   31,   12,   33,   12,   34,  184,   32,
       33,   39,   34,   47,  180,    3,    4,   22,   35,   35,
       22,   36,   40,   36,   38,   22,   41,   41,   48,   48,
       38,   34,   22,  172,   22,   59,   34,   22,   38,   50,
       50,   22,   35,   35,   22,   36,   40,   36,   38,   22,
       41,   41,  102,  102,   38,  101,   22,   58,   22,   59,
       60,   22,   38,   52,   56,   58,   56,   56,   56,   61,
       62,   63,   52,   67,   52,   68,   52,   52,   52,   52,

       69,   58,   70,   71,   60,   72,   73,   52,   74,   58,
       75,   76,   80,   61,   62,   63,   52,   67,   52,   68,
       52,   52,   52,   52,   69,   81,   70,   71,   79,   72,
       73,   82,   74,   79,   75,   76,   80,   83,   84,   86,
       87,   88,   89,   90,   91,   87,   93,   94,   95,   81,
      105,  106,   79,  107,  108,   82,  110,   79,  111,  109,
      112,   83,   84,   86,   87,   88,   89,   90,   91,   87,
       93,   94,   95,  109,  105,  106,  113,  107,  108,  114,
      110,  115,  111,  109,  112,  116,  117,  118,  120,  121,
      122,  123,  125,  126,  127,  128,  129,  109,  131,  132,

      113,  135,  122,  114,  136,  115,  122,  137,  138,  116,
      117,  118,  120,  121,  122,  123,  125,  126,  127,  128,
      129,  139,  131,  132,  140,  135,  122,  141,  136,  142,
      122,  137,  138,  143,  144,  145,  146,  147,  148,  149,
      150,  151,  152,  153,  154,  139,  155,  156,  140,  157,
      158,  141,  159,  142,  160,  161,  162,  143,  144,  145,
      146,  147,  148,  149,  150,  151,  152,  153,  154,  163,
      155,  156,  164,  157,  158,  165,  159,  166,  160,  161,
      162,  168,  170,  171,  175,  176,  177,  178,  181,  182,
      183,  185,  186,  163,  187,  188,  164,  189,  190,  165,

      191,  166,  193,  194,  195,  168,  170,  171,  175,  176,
      177,  178,  181,  182,  183,  185,  186,  197,  187,  188,
      196,  189,  190,  199,  191,  196,  193,  194,  195,  201,
      202,  203,  205,  206,  207,  208,  209,  210,  213,  214,
      215,  197,  216,  218,  196,  219,  220,  199,  221,  196,
      223,  224,  225,  201,  202,  203,  205,  206,  207,  208,
      209,  210,  213,  214,  215,  226,  216,  218,  227,  219,
      220,  228,  221,  229,  223,  224,  225,  230,  231,  232,
      233,  234,  235,  236,  238,  240,  241,  243,  244,  226,
      246,  247,  227,  248,  249,  228,  250,  229,  251,  253,

      254,  230,  231,  232,  233,  234,  235,  236,  238,  240,
      241,  243,  244,  255,  246,  247,  256,  248,  249,  257,
      250,  260,  251,  253,  254,  261,  262,  265,  266,  267,
      268,  269,  270,  271,  272,  273,  276,  255,  277,  278,
      256,  280,  281,  257,  283,  260,  284,  286,  287,  261,
      262,  265,  266,  267,  268,  269,  270,  271,  272,  273,
      276,  289,  277,  278,  288,  280,  281,  290,  283,  288,
      284,  286,  287,  291,  294,  295,  297,  298,  299,  300,
      301,  302,  303,  305,  307,  289,  308,  309,  288,  310,
      311,  290,  315,  288,  316,  319,  321,  291,  294,  295,

      297,  298,  299,  300,  301,  302,  303,  305,  307,  324,
      308,  309,  325,  310,  311,  327,  315,  328,  316,  319,
      321,  329,   49,   44,   26,   24,    7,    0,    0,    0,
        0,    0,    0,  324,    0,    0,  325,    0,    0,  327,
        0,  328,    0,    0,    0,  329,  333,  333,  333,  333,
      333,  333,  333,  334,  334,  334,  334,  334,  334,  334,
      335,  335,  336,  336,  337,  337,    0,  337,  337,  337,
      337,  338,  338,  338,  338,    0,  338,  338,  339,  339,
      339,    0,  339,  339,  339,  341,    0,    0,  341,  341,
      341,  341,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.flex"
#line 2 "lexer.flex"

#include <string.h>
#include <ctype.h>
#include "parser.tab.h"

int my_powah(int base, int n)
{
    int result = 1;
    for (int i = 0; i < n; i++)
        result *= base;
    return result;
}

int nondec2dec(char * string, int base)
{
    int result = 0;
    size_t length = strlen(string);
    for (size_t i = 0; i < length; i++)
    {
        char cur = string[length - i - 1];
        int tmp = 0;
        switch (cur)
        {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            tmp = (int)cur - 0x30;
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
            tmp = (int)cur - ('A' - 0xA);
            break;
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
            tmp = (int)cur - ('a' - 0xA);
            break;
        default:
            tmp = 0;
        }
        result += tmp * my_powah(base, i);
    }
    return result;
}

void store_function_id() {
    yylval.semantic_id = (char *)malloc(sizeof(char) * (yyleng + 1));
    strcpy(yylval.semantic_id, yytext);
    for (size_t i = 0; i < yyleng; i++)
        yylval.semantic_id[i] = tolower(yylval.semantic_id[i]);
}



#line 805 "lexer.c"

#define INITIAL 0
#define COMMENT_ML_ST 1
#define STRING_ST 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 86 "lexer.flex"



char            buffer[8 * 1024];   // For storing strings, comments etc.
unsigned int    buffer_length = 0;  // Length of the buffer.


#line 997 "lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 333 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 332 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 93 "lexer.flex"
{
    // Multiline comment beginning.
    BEGIN(COMMENT_ML_ST);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "lexer.flex"
{
    // String constant beginning.
    buffer_length = 0;
    BEGIN(STRING_ST);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 102 "lexer.flex"
{
    // Singleline comment, do nothing.
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 105 "lexer.flex"
{
    // Whitespaces, do nothing.
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "lexer.flex"
{
    // Opening parenthesis.
    return (unsigned char)'(';
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 112 "lexer.flex"
{
    // Closing parenthesis.
    return (unsigned char)')';
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "lexer.flex"
{
    // Operator: addition.
    store_function_id();
    return ID;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "lexer.flex"
{
    // Operator: subtraction.
    store_function_id();
    return ID;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 126 "lexer.flex"
{
    // Operator: multiplication.
     store_function_id();
    return ID;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "lexer.flex"
{
    // Operator: division.
    store_function_id();
    return ID;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "lexer.flex"
{
    // Operator: greater.
    store_function_id();
    return ID;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 141 "lexer.flex"
{
    // Operator: greater or equal.
    store_function_id();
    return ID;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "lexer.flex"
{
    // Operator: less.
    store_function_id();
    return ID;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 151 "lexer.flex"
{
    // Operator: less or equal.
    store_function_id();
    return ID;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 156 "lexer.flex"
{
    // Operator: equal.
    store_function_id();
    return ID;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 161 "lexer.flex"
{
    // Operator: and.
    store_function_id();
    return ID;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 166 "lexer.flex"
{
    // Operator: or.
    store_function_id();
    return ID;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 171 "lexer.flex"
{
    // Operator: not.
    store_function_id();
    return ID;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 176 "lexer.flex"
{
    // Boolean constant - true.
    yylval.semantic_bool = 1;
    return BOOL;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 181 "lexer.flex"
{
    // Boolean constant - false.
    yylval.semantic_bool = 0;
    return BOOL;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 186 "lexer.flex"
{
    // Numeric constant - binary.
    yylval.semantic_int = nondec2dec(yytext + 2, 2);
    return INT;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 191 "lexer.flex"
{
    // Numeric constant - octal.
    yylval.semantic_int = nondec2dec(yytext + 2, 8);
    return INT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 196 "lexer.flex"
{
    // Numeric constant.
    if (yytext[yyleng - 1] == '.')
        yytext[yyleng - 1] = '\0';
    yylval.semantic_int = nondec2dec(yytext, 10);
    return INT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 203 "lexer.flex"
{
    // Numeric constant - hexadecimal.
    yylval.semantic_int = nondec2dec(yytext + 2, 16);
    return INT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 208 "lexer.flex"
{
    // Character constant.
    yylval.semantic_char = yytext[2];
    return CHAR;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 213 "lexer.flex"
{
    // Character constant - whitespace.
    yylval.semantic_char = 'q'; // TODO: convert to a real character.
    return CHAR;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 218 "lexer.flex"
{
    return LOOP;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 221 "lexer.flex"
{
    return FOR;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 224 "lexer.flex"
{
    return IN;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 227 "lexer.flex"
{
    return DO;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 230 "lexer.flex"
{
    return FROM;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 233 "lexer.flex"
{
    return TO;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 236 "lexer.flex"
{
    return WHILE;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 239 "lexer.flex"
{
    return PROGN;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 242 "lexer.flex"
{
    return DEFPARAMETER;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 245 "lexer.flex"
{
    return SETF;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "lexer.flex"
{
    return LET;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 251 "lexer.flex"
{
    return VECTOR;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 254 "lexer.flex"
{
    return VECTORPUSH;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 257 "lexer.flex"
{
    return VECTORPOP;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 260 "lexer.flex"
{
    return ELT;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 263 "lexer.flex"
{
    return LIST;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 266 "lexer.flex"
{
    return LISTLENGTH;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 269 "lexer.flex"
{
    return LENGTH;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 272 "lexer.flex"
{
    return FIND;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 275 "lexer.flex"
{
    return POSITION;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 278 "lexer.flex"
{
    return REMOVE;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 281 "lexer.flex"
{
    return SUBSTITUTE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 284 "lexer.flex"
{
    return CONCATENATE;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 287 "lexer.flex"
{
    return IF;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 290 "lexer.flex"
{
    return DOTIMES;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 293 "lexer.flex"
{
    return DEFUN;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 296 "lexer.flex"
{
    return SLOTVALUE;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 299 "lexer.flex"
{
    return OPEN;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 302 "lexer.flex"
{
    return CLOSE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 305 "lexer.flex"
{
    return WITHOPENFILE;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 308 "lexer.flex"
{
    return FORMAT;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 311 "lexer.flex"
{
    return FUNCALL;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 314 "lexer.flex"
{
    return DEFCLASS;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 317 "lexer.flex"
{
    return (unsigned char)'\'';
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 320 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 323 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 326 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 329 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 332 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 335 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 338 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 341 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 344 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 347 "lexer.flex"
{
    printf("Key word:                  %s\n", yytext);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 350 "lexer.flex"
{
    // User-defined symbol.
    store_function_id();
    return ID;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 355 "lexer.flex"
{
    printf("UNEXPECTED CHARACTER:      %s\n", yytext);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 358 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 361 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 364 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 367 "lexer.flex"
{
    // Multiline comment ending.
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(COMMENT_ML_ST):
#line 371 "lexer.flex"
{
    puts("ERROR: UNCLOSED COMMENT");
    yyterminate();
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 375 "lexer.flex"
{
    // String constant body: escaped quote character.
    buffer[buffer_length++] = '"';
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 379 "lexer.flex"
{
    // String constant body: escaped slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 383 "lexer.flex"
{
    // String constant body: non-quote, non-slash characters.
    for (int i = 0; i < yyleng; i++)
        buffer[buffer_length++] = yytext[i];
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 388 "lexer.flex"
{
    // String constant body: unrecognized slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 392 "lexer.flex"
{
    // String constant ending.
    yylval.semantic_string = (char *)malloc(sizeof(char) * (buffer_length + 1));
    strcpy(yylval.semantic_string, buffer);
    buffer_length = 0;
    BEGIN(INITIAL);
    return STRING;
}
	YY_BREAK
case YY_STATE_EOF(STRING_ST):
#line 400 "lexer.flex"
{
    puts("ERROR: UNCLOSED STRING CONSTANT");
    yyterminate();
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 405 "lexer.flex"
ECHO;
	YY_BREAK
#line 1725 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 333 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 333 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 332);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 405 "lexer.flex"



