#line 2 "lexer.cpp"

#line 4 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[337] =
    {   0,
        0,    0,    0,    0,    0,    0,   84,   72,    4,    4,
        2,   72,   70,    5,    6,    7,   10,    8,    9,   11,
       44,   72,    3,   14,   16,   12,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   40,
       70,   70,   72,   75,   74,   73,   80,   82,   81,    4,
        0,    0,    0,    0,    1,   70,    0,   44,   44,   69,
       69,   69,   69,   69,   69,    3,   15,   13,   70,   70,
       70,   70,   51,   70,   70,   70,   70,   70,   56,   50,
       70,   70,   70,   70,   70,   70,   70,   18,   70,   70,
       70,   70,   70,   70,   53,   70,   70,   70,    0,   75,

       76,   80,   77,   79,   78,   42,   43,   45,   46,   46,
       46,   46,   46,   46,   46,   46,   69,   69,   69,   69,
       69,   69,   17,   70,   70,   70,   27,   70,   49,   70,
       70,   70,   23,   70,   70,   70,   41,   19,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   71,
        0,    0,    0,    0,    0,    0,    0,    0,   69,   69,
       69,   69,   69,   69,   69,   70,   70,   70,   70,   70,
       70,   31,   52,   70,   70,   28,   48,   70,   36,   70,
       70,   70,   70,   22,   70,   70,   70,   70,   70,    0,
        0,    0,    0,    0,    0,    0,   47,   69,   69,   69,

       69,   69,   69,   69,   37,   70,   70,   70,   58,   70,
       70,   70,   70,   70,   70,   39,   55,   70,   70,   70,
       70,   54,   70,    0,    0,    0,   47,    0,    0,    0,
       69,   69,   66,   69,   69,   69,   69,   70,   70,   70,
       21,   70,   30,   70,   70,   70,   33,   70,   70,   24,
       70,    0,    0,    0,    0,    0,   47,   69,   69,   69,
       69,   61,   62,   70,   70,   70,   59,   70,   70,   70,
       70,   70,   70,   70,    0,    0,    0,   47,   47,   69,
       69,   69,   69,   70,   57,   70,   70,   70,   32,   70,
       70,   70,   70,    0,    0,   47,   63,   69,   60,   65,

       70,   70,   70,   70,   70,   70,   70,   70,   70,    0,
       47,   69,   70,   70,   70,   70,   68,   34,   26,   70,
       70,   47,   64,   35,   70,   29,   70,   25,   70,   20,
       70,   70,   67,   70,   38,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    6,    6,    7,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,    1,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,    6,   32,   33,   34,   35,   36,   37,
        6,   38,   39,   40,   41,   42,   43,   44,    6,    6,
        1,   45,    1,    6,    6,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,    6,   55,   56,   57,   58,
       59,   60,    6,   61,   62,   63,   64,   65,   66,   67,
        6,    6,    1,   68,    1,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    2,    3,    4,    5,    6,    1,    1,    1,    6,
        6,    6,    6,    6,    7,    7,    7,    1,    1,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    4,    7,    7,    7,    7,    7,
        7,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    5
    } ;

static yyconst flex_int16_t yy_base[347] =
    {   0,
        0,    0,   64,   65,   67,   68,  632,  703,   71,   73,
      703,   55,    0,  703,  703,  703,    0,    0,   72,    0,
       65,   73,    0,  610,    0,  609,   48,   59,   58,   51,
       99,   96,  114,   63,   89,   91,  100,   76,  129,  106,
      117,  141,    0,    0,  703,  624,    0,  703,  142,  172,
      613,  165,    0,  177,  703,    0,  152,  189,    0,    0,
      165,  122,  131,  142,  146,    0,    0,    0,  160,  161,
      168,  180,    0,  178,  187,  185,  189,  192,    0,    0,
      194,  189,  194,  200,  203,  202,  216,    0,  205,  218,
      213,  216,  222,  236,    0,  236,  231,  223,  234,    0,

      703,    0,  703,  703,  703,  176,  167,    0,  703,  241,
      237,  242,  248,  247,  236,  252,  251,  245,  257,  251,
      266,  262,    0,  256,  275,  283,    0,  278,    0,  272,
      282,  280,    0,  270,  277,  288,    0,    0,  282,  288,
      286,  293,  290,  300,  294,  296,  296,  306,  311,   89,
      321,  315,  309,  324,  314,  331,  333,  336,  334,  327,
      326,  326,  327,  342,  330,  344,  349,  341,  357,  346,
      359,    0,    0,  362,  347,  137,    0,   98,    0,  352,
      356,  363,  357,    0,   93,  360,  365,  375,   89,  374,
      380,  376,  384,  371,  377,  389,  703,  377,  392,  379,

      392,  403,  400,  401,    0,  391,  410,  400,    0,  404,
      411,  415,  413,  416,  417,    0,    0,  425,  411,  424,
      419,    0,  422,  420,  432,  431,  703,  425,  423,  439,
      433,  450,    0,  438,  442,  441,  446,  461,  451,  468,
        0,  459,    0,  466,  459,  462,    0,  476,  461,   85,
      466,  467,  478,  471,  473,  469,  703,  474,  472,  480,
      494,    0,    0,  485,  484,  491,    0,  495,  495,  501,
      504,  497,  502,  513,  521,  518,  520,  703,  703,  511,
      519,  517,  525,  531,    0,  528,  527,  518,    0,  523,
      525,  530,  534,  551,  554,  703,    0,  546,    0,    0,

      543,  544,  545,  563,  563,  564,  556,  556,   81,  569,
      703,  562,  571,  573,  571,  567,    0,    0,    0,  574,
      582,  703,    0,    0,  573,    0,  587,    0,  584,    0,
      590,  589,    0,  599,    0,  703,  649,  656,  658,  660,
      667,  674,  681,  688,   83,  695
    } ;

static yyconst flex_int16_t yy_def[347] =
    {   0,
      336,    1,  337,  337,  338,  338,  336,  336,  336,  336,
      336,  336,  339,  336,  336,  336,  339,  339,  339,  339,
      339,  340,  341,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  342,  343,  336,  336,  344,  336,  336,  336,
      336,  336,  345,  346,  336,  339,  336,  339,  339,  340,
      340,  340,  340,  340,  340,  341,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  342,  343,

      336,  344,  336,  336,  336,  336,  336,  345,  336,  336,
      336,  336,  336,  336,  336,  336,  340,  340,  340,  340,
      340,  340,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  342,
      336,  336,  336,  336,  336,  336,  336,  336,  340,  340,
      340,  340,  340,  340,  340,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  336,
      336,  336,  336,  336,  336,  336,  336,  340,  340,  340,

      340,  340,  340,  340,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  336,  336,  336,  336,  336,  336,  336,
      340,  340,  340,  340,  340,  340,  340,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  336,  336,  336,  336,  336,  336,  340,  340,  340,
      340,  340,  340,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  336,  336,  336,  336,  336,  340,
      340,  340,  340,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  336,  336,  336,  340,  340,  340,  340,

      339,  339,  339,  339,  339,  339,  339,  339,  339,  336,
      336,  340,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  336,  340,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,    0,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336
    } ;

static yyconst flex_int16_t yy_nxt[772] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   13,   20,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   13,   28,   29,   30,   31,   13,   13,
       32,   13,   33,   34,   35,   36,   37,   38,   39,   40,
       13,   41,   42,   13,    8,   27,   13,   28,   29,   30,
       31,   13,   13,   32,   13,   33,   34,   35,   36,   37,
       38,   39,   40,   13,   41,   42,   13,   43,   45,   45,
       48,   48,   50,   50,   50,   50,   57,   59,   51,   58,
       58,   58,   69,   74,   72,   84,   58,   58,   58,  108,
       52,   70,  321,   73,   71,   61,  273,   62,   53,   54,

      223,   51,   91,   63,  219,   69,   74,   72,   84,  214,
       64,   49,   49,   52,   70,   65,   73,   71,   61,   85,
       62,   53,   55,   79,   86,   91,   63,   87,   88,   75,
       80,   46,   46,   64,   76,   89,   77,   90,   65,   78,
       81,   95,   85,   96,   82,  103,   79,   86,  213,   83,
       87,   88,   75,   80,  119,   92,  150,   76,   89,   77,
       90,   93,   78,   81,   95,  120,   96,   82,  121,   94,
       97,   98,   83,   50,   50,   51,  104,  119,   92,  107,
      107,  107,  107,  122,   93,  123,  105,   52,  120,  117,
      106,  121,   94,   97,   98,   53,  124,  118,   51,  104,

      110,   59,  125,   58,   58,   58,  122,  126,  123,  111,
       52,  112,  117,  113,  114,  115,  116,  127,   53,  124,
      118,  128,  129,  110,  130,  125,  131,  134,  132,  135,
      126,  136,  111,  133,  112,  137,  113,  114,  115,  116,
      127,  138,  139,  140,  128,  129,  143,  130,  141,  131,
      134,  132,  135,  142,  136,  144,  133,  145,  137,  146,
      147,  148,  149,  151,  138,  139,  140,  152,  153,  143,
      154,  141,  157,  155,  158,  159,  142,  160,  144,  161,
      145,  162,  146,  147,  148,  149,  151,  156,  164,  163,
      152,  153,  165,  154,  166,  157,  155,  158,  159,  167,

      160,  150,  161,  172,  162,  173,  174,  168,  175,  176,
      156,  164,  163,  177,  178,  165,  179,  166,  180,  169,
      181,  182,  167,  170,  171,  183,  172,  184,  173,  174,
      168,  175,  176,  185,  186,  187,  177,  178,  188,  179,
      189,  180,  169,  181,  182,  190,  170,  171,  183,  191,
      184,  192,  193,  194,  195,  196,  185,  186,  187,  197,
      198,  188,  199,  189,  200,  201,  202,  203,  190,  204,
      205,  206,  191,  207,  192,  193,  194,  195,  196,  208,
      209,  210,  197,  198,  211,  199,  212,  200,  201,  202,
      203,  215,  204,  205,  206,  216,  207,  217,  218,  220,

      221,  222,  208,  209,  210,  224,  225,  211,  226,  212,
      227,  228,  229,  230,  215,  231,  232,  233,  216,  234,
      217,  218,  220,  221,  222,  235,  236,  237,  224,  225,
      238,  226,  239,  227,  228,  229,  230,  240,  231,  232,
      233,  241,  234,  242,  243,  244,  245,  246,  235,  236,
      237,  247,  248,  238,  249,  239,  250,  251,  252,  253,
      240,  254,  255,  256,  241,  257,  242,  243,  244,  245,
      246,  258,  259,  260,  247,  248,  261,  249,  262,  250,
      251,  252,  253,  263,  254,  255,  256,  264,  257,  265,
      266,  267,  268,  269,  258,  259,  260,  270,  271,  261,

      272,  262,  274,  275,  276,  277,  263,  278,  279,  280,
      264,  281,  265,  266,  267,  268,  269,  282,  283,  284,
      270,  271,  285,  272,  286,  274,  275,  276,  277,  287,
      278,  279,  280,  288,  281,  289,  290,  291,  292,  293,
      282,  283,  284,  294,  295,  285,  296,  286,  297,  298,
      299,  300,  287,  301,  302,  303,  288,  304,  289,  290,
      291,  292,  293,  305,  306,  307,  294,  295,  309,  296,
      308,  297,  298,  299,  300,  310,  301,  302,  303,  311,
      304,  312,  313,  314,  315,  316,  305,  306,  307,  317,
      318,  309,  319,  308,  320,  322,  323,  324,  310,  325,

      326,  327,  311,  328,  312,  313,  314,  315,  316,  329,
      330,  331,  317,  318,  332,  319,  333,  320,  322,  323,
      324,  334,  325,  326,  327,  335,  328,  106,  101,   68,
       67,  336,  329,  330,  331,  336,  336,  332,  336,  333,
      336,  336,  336,  336,  334,  336,  336,  336,  335,   44,
       44,   44,   44,   44,   44,   44,   47,   47,   47,   47,
       47,   47,   47,   56,   56,   60,   60,   66,   66,  336,
       66,   66,   66,   66,   99,   99,  336,   99,   99,   99,
       99,  100,  100,  100,  100,  336,  100,  100,  102,  102,
      102,  336,  102,  102,  102,  109,  336,  336,  109,  109,

      109,  109,    7,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336
    } ;

static yyconst flex_int16_t yy_chk[772] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,    9,    9,   10,   10,   19,   21,   12,   21,
       21,   21,   27,   30,   29,   34,   19,   19,   19,  345,
       12,   28,  309,   29,   28,   22,  250,   22,   12,   12,

      189,   12,   38,   22,  185,   27,   30,   29,   34,  178,
       22,    5,    6,   12,   28,   22,   29,   28,   22,   35,
       22,   12,   12,   32,   35,   38,   22,   36,   36,   31,
       32,    3,    4,   22,   31,   37,   31,   37,   22,   31,
       33,   40,   35,   41,   33,   49,   32,   35,  176,   33,
       36,   36,   31,   32,   62,   39,  150,   31,   37,   31,
       37,   39,   31,   33,   40,   63,   41,   33,   64,   39,
       42,   42,   33,   50,   50,   57,   49,   62,   39,   52,
       52,  107,  107,   65,   39,   69,   49,   57,   63,   61,
      106,   64,   39,   42,   42,   57,   70,   61,   57,   49,

       54,   58,   71,   58,   58,   58,   65,   72,   69,   54,
       57,   54,   61,   54,   54,   54,   54,   74,   57,   70,
       61,   75,   76,   54,   77,   71,   78,   82,   81,   83,
       72,   84,   54,   81,   54,   85,   54,   54,   54,   54,
       74,   86,   87,   89,   75,   76,   91,   77,   90,   78,
       82,   81,   83,   90,   84,   92,   81,   93,   85,   94,
       96,   97,   98,  110,   86,   87,   89,  111,  112,   91,
      113,   90,  115,  114,  116,  117,   90,  118,   92,  119,
       93,  120,   94,   96,   97,   98,  110,  114,  121,  120,
      111,  112,  122,  113,  124,  115,  114,  116,  117,  125,

      118,   99,  119,  128,  120,  130,  131,  126,  132,  134,
      114,  121,  120,  135,  136,  122,  139,  124,  140,  126,
      141,  142,  125,  126,  126,  143,  128,  144,  130,  131,
      126,  132,  134,  145,  146,  147,  135,  136,  148,  139,
      149,  140,  126,  141,  142,  151,  126,  126,  143,  152,
      144,  153,  154,  155,  156,  157,  145,  146,  147,  158,
      159,  148,  160,  149,  161,  162,  163,  164,  151,  165,
      166,  167,  152,  168,  153,  154,  155,  156,  157,  169,
      170,  171,  158,  159,  174,  160,  175,  161,  162,  163,
      164,  180,  165,  166,  167,  181,  168,  182,  183,  186,

      187,  188,  169,  170,  171,  190,  191,  174,  192,  175,
      193,  194,  195,  196,  180,  198,  199,  200,  181,  201,
      182,  183,  186,  187,  188,  202,  203,  204,  190,  191,
      206,  192,  207,  193,  194,  195,  196,  208,  198,  199,
      200,  210,  201,  211,  212,  213,  214,  215,  202,  203,
      204,  218,  219,  206,  220,  207,  221,  223,  224,  225,
      208,  226,  228,  229,  210,  230,  211,  212,  213,  214,
      215,  231,  232,  234,  218,  219,  235,  220,  236,  221,
      223,  224,  225,  237,  226,  228,  229,  238,  230,  239,
      240,  242,  244,  245,  231,  232,  234,  246,  248,  235,

      249,  236,  251,  252,  253,  254,  237,  255,  256,  258,
      238,  259,  239,  240,  242,  244,  245,  260,  261,  264,
      246,  248,  265,  249,  266,  251,  252,  253,  254,  268,
      255,  256,  258,  269,  259,  270,  271,  272,  273,  274,
      260,  261,  264,  275,  276,  265,  277,  266,  280,  281,
      282,  283,  268,  284,  286,  287,  269,  288,  270,  271,
      272,  273,  274,  290,  291,  292,  275,  276,  293,  277,
      292,  280,  281,  282,  283,  294,  284,  286,  287,  295,
      288,  298,  301,  302,  303,  304,  290,  291,  292,  305,
      306,  293,  307,  292,  308,  310,  312,  313,  294,  314,

      315,  316,  295,  320,  298,  301,  302,  303,  304,  321,
      325,  327,  305,  306,  329,  307,  331,  308,  310,  312,
      313,  332,  314,  315,  316,  334,  320,   51,   46,   26,
       24,    7,  321,  325,  327,    0,    0,  329,    0,  331,
        0,    0,    0,    0,  332,    0,    0,    0,  334,  337,
      337,  337,  337,  337,  337,  337,  338,  338,  338,  338,
      338,  338,  338,  339,  339,  340,  340,  341,  341,    0,
      341,  341,  341,  341,  342,  342,    0,  342,  342,  342,
      342,  343,  343,  343,  343,    0,  343,  343,  344,  344,
      344,    0,  344,  344,  344,  346,    0,    0,  346,  346,

      346,  346,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.flex"
#line 2 "lexer.flex"

#include <string.h>
#include <ctype.h>
#include "parser.hpp"
#include "errors.h"

int my_powah(int base, int n)
{
    int result = 1;
    for (int i = 0; i < n; i++)
        result *= base;
    return result;
}

int nondec2dec(char * string, int base)
{
    int result = 0;
    size_t length = strlen(string);
    for (size_t i = 0; i < length; i++)
    {
        char cur = string[length - i - 1];
        int tmp = 0;
        switch (cur)
        {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            tmp = (int)cur - 0x30;
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
            tmp = (int)cur - ('A' - 0xA);
            break;
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
            tmp = (int)cur - ('a' - 0xA);
            break;
        default:
            tmp = 0;
        }
        result += tmp * my_powah(base, i);
    }
    return result;
}

void store_function_id(const char * id) {
    size_t length = strlen(id);
    yylval.semantic_id = (char *)malloc(sizeof(char) * (length + 1));
    strcpy(yylval.semantic_id, id);
    for (size_t i = 0; i < length; i++)
        yylval.semantic_id[i] = tolower(yylval.semantic_id[i]);
}



#line 809 "lexer.cpp"

#define INITIAL 0
#define COMMENT_ML_ST 1
#define STRING_ST 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 88 "lexer.flex"



char            buffer[8 * 1024];   // For storing strings, comments etc.
unsigned int    buffer_length = 0;  // Length of the buffer.


#line 1001 "lexer.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 337 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 336 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 95 "lexer.flex"
{
    // Multiline comment beginning.
    BEGIN(COMMENT_ML_ST);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "lexer.flex"
{
    // String constant beginning.
    buffer_length = 0;
    BEGIN(STRING_ST);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 104 "lexer.flex"
{
    // Singleline comment, do nothing.
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 107 "lexer.flex"
{
    // Whitespaces, do nothing.
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 110 "lexer.flex"
{
    return (unsigned char)'\'';
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 113 "lexer.flex"
{
    // Opening parenthesis.
    return (unsigned char)'(';
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 117 "lexer.flex"
{
    // Closing parenthesis.
    return (unsigned char)')';
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "lexer.flex"
{
    // Operator: addition.
    store_function_id("plus");
    return ID;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 126 "lexer.flex"
{
    // Operator: subtraction.
    store_function_id("minus");
    return ID;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "lexer.flex"
{
    // Operator: multiplication.
     store_function_id("mult");
    return ID;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "lexer.flex"
{
    // Operator: division.
    store_function_id("div");
    return ID;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 141 "lexer.flex"
{
    // Operator: greater.
    store_function_id("greater");
    return ID;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "lexer.flex"
{
    // Operator: greater or equal.
    store_function_id("greater_eq");
    return ID;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 151 "lexer.flex"
{
    // Operator: less.
    store_function_id("less");
    return ID;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 156 "lexer.flex"
{
    // Operator: less or equal.
    store_function_id("less_eq");
    return ID;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 161 "lexer.flex"
{
    // Operator: equal.
    store_function_id("eq");
    return ID;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 166 "lexer.flex"
{
    // Operator: and.
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 171 "lexer.flex"
{
    // Operator: or.
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 176 "lexer.flex"
{
    // Operator: not.
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 181 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 185 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 189 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 193 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 197 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 201 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 205 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 209 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 213 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 217 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 221 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 225 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 229 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 237 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 241 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 245 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 249 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 253 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 257 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 261 "lexer.flex"
{
    // Boolean constant - true.
    yylval.semantic_bool = 1;
    return BOOL;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 266 "lexer.flex"
{
    // Boolean constant - false.
    yylval.semantic_bool = 0;
    return BOOL;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 271 "lexer.flex"
{
    // Numeric constant - binary.
    int shift = (yytext[0] == '-') ? 1 : 0;
    int sign = shift ? -1 : 1;
    yylval.semantic_int = sign * nondec2dec(yytext + 2 + shift, 2);
    return INT;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 278 "lexer.flex"
{
    // Numeric constant - octal.
    int shift = (yytext[0] == '-') ? 1 : 0;
    int sign = shift ? -1 : 1;
    yylval.semantic_int = sign * nondec2dec(yytext + 2 + shift, 8);
    return INT;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 285 "lexer.flex"
{
    // Numeric constant.
    if (yytext[yyleng - 1] == '.')
        yytext[yyleng - 1] = '\0';
    int shift = (yytext[0] == '-') ? 1 : 0;
    int sign = shift ? -1 : 1;
    yylval.semantic_int = sign * nondec2dec(yytext + shift, 10);
    return INT;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 294 "lexer.flex"
{
    // Numeric constant - hexadecimal.
    int shift = (yytext[0] == '-') ? 1 : 0;
    int sign = shift ? -1 : 1;
    yylval.semantic_int = sign * nondec2dec(yytext + 2 + shift, 16);
    return INT;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 301 "lexer.flex"
{
    // Character constant.
    yylval.semantic_char = yytext[2];
    return CHAR;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 306 "lexer.flex"
{
    // Character constant - whitespace.
    yylval.semantic_char = 'q'; // TODO: convert to a real character.
    return CHAR;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 311 "lexer.flex"
{
    return LOOP;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 314 "lexer.flex"
{
    return FOR;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 317 "lexer.flex"
{
    return IN;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 320 "lexer.flex"
{
    return DO;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 323 "lexer.flex"
{
    return FROM;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 326 "lexer.flex"
{
    return TO;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 329 "lexer.flex"
{
    return WHILE;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 332 "lexer.flex"
{
    return PROGN;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 335 "lexer.flex"
{
    return IF;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 338 "lexer.flex"
{
    return DEFCLASS;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 341 "lexer.flex"
{
    return DEFUN;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 344 "lexer.flex"
{
    return FUNCALL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 347 "lexer.flex"
{
    return INITFORM;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 350 "lexer.flex"
{
    return READER;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 353 "lexer.flex"
{
    return WRITER;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 356 "lexer.flex"
{
    return ACCESSOR;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 359 "lexer.flex"
{
    return ALLOCATION;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 362 "lexer.flex"
{
    return ALLOCINSTANCE;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 365 "lexer.flex"
{
    return ALLOCCLASS;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 368 "lexer.flex"
{
    return MAKEINSTANCE;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 371 "lexer.flex"
{
    return SLOTVALUE;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 374 "lexer.flex"
{
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 378 "lexer.flex"
{
    // User-defined symbol.
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 383 "lexer.flex"
{
    // User-defined symbol.
    store_function_id(yytext);
    return ID;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 388 "lexer.flex"
{
    return ERROR_UNEXPECTED_CHARACTER;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 391 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 394 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 397 "lexer.flex"
{
    // Multiline comment body: any character.
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 400 "lexer.flex"
{
    // Multiline comment ending.
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(COMMENT_ML_ST):
#line 404 "lexer.flex"
{
    return ERROR_UNCLOSED_COMMENT;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 407 "lexer.flex"
{
    // String constant body: escaped quote character.
    buffer[buffer_length++] = '"';
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 411 "lexer.flex"
{
    // String constant body: escaped slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 415 "lexer.flex"
{
    // String constant body: newline.
    buffer[buffer_length++] = '\n';
}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 419 "lexer.flex"
{
    // String constant body: non-quote, non-slash characters.
    for (int i = 0; i < yyleng; i++)
        buffer[buffer_length++] = yytext[i];
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 424 "lexer.flex"
{
    // String constant body: unrecognized slash character.
    buffer[buffer_length++] = '\\';
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 428 "lexer.flex"
{
    // String constant ending.
    buffer[buffer_length] = '\0';
    yylval.semantic_string = (char *)malloc(sizeof(char) * (buffer_length + 1));
    strcpy(yylval.semantic_string, buffer);
    buffer_length = 0;
    BEGIN(INITIAL);
    return STRING;
}
	YY_BREAK
case YY_STATE_EOF(STRING_ST):
#line 437 "lexer.flex"
{
    return ERROR_UNCLOSED_STRING;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 441 "lexer.flex"
ECHO;
	YY_BREAK
#line 1767 "lexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 337 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 337 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 336);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 441 "lexer.flex"



